### ISSUE TITLE
how to create table “settings”

### ISSUE THREAD

**Issue by kazu12** [metrico/qryn#161]
I use k8s deploy cLoki. when it begin to run, I get a error:
`{"level":50,"time":1652663995707,"pid":19,"hostname":"cloki-76c77bc778-ps6tp","name":"cloki","err":"Error: Request failed with status code 404\nResponse: [404] Code: 60, e.displayText() = DB::Exception: Table loki.settings doesn't exist (version 21.1.3.32)\n\nError: Request failed with status code 404\n    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at endReadableNT (internal/streams/readable.js:1334:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)","msg":"Error starting cloki"}
`
how to do with it?

**Comment by lmangani** [comment]
This is [how](https://github.com/lmangani/cLoki/blob/master/lib/db/maintain/scripts.js) but it should be done by cloki during init. Are you using our container, or building your own? Please share more details and we'll try to replicate.

**Comment by kazu12** [comment]
I had already created two tables， the "samples" and the "time_series"

**Comment by lmangani** [comment]
qryn should create (or update) its owned tables when connecting to the database or cluster - is there anything preventing that from happening? Could you confirm if this is still an issue?

**Comment by akvlad** [comment]
I'm walking through old issues.
@kazu12  is this issue still relevant for now?

**Comment by kazu12** [comment]
sorry for delay replied message。I have not update the latest version. I play update it next week.

think for responese. I will try it.

**Comment by lmangani** [comment]
Feel free to reopen if still interested for 3.x
