### ISSUE TITLE
loki explore "show context" error

### ISSUE THREAD

**Issue by wangchaoforever** [metrico/qryn#168]
when I use grafana Loki explore, I click "show context" to show the context, but it throw an ERROR:
![image](https://user-images.githubusercontent.com/46668848/174032119-fe1b4b7d-5c74-4826-a6f8-145cd851ca51.png)
I also find the qryn server log:  Cannot read properties of null (reading 'rootToken')

**Comment by akvlad** [comment]
Well, this function was always flawed on the Grafana side. I'll recheck the latest version, but for the most cases at the past the Grafana client was just sending a corrupted request.

Well, if it's possible, can you paste a request Grafana sends on 'show context' button? Maybe some "***" signs for label names/values are OK. Or you can just check yourself if the show context request is legit according to the logql syntax.

Please provide the Grafana version you use so I can review the state of the problem.

**Comment by wangchaoforever** [comment]
Thank you for timely reply.

**Comment by wangchaoforever** [comment]
Thank you for timely reply. My local grafana is 7.x. I will upgrade my grafana to 8.x to verify this problem.

**Comment by wangchaoforever** [comment]
@akvlad When I upgrade my grafana to 8.x, the problem is still exist.

**Comment by wangchaoforever** [comment]
![image](https://user-images.githubusercontent.com/46668848/174050437-c5181dcd-5f12-4be7-8677-ebb0fd5a0746.png)
when the "time" button is turned on, there are two timestamps in my logs, is it affet the "show context"?

**Comment by akvlad** [comment]
@wangchaoforever The first time is the timestamp when qryn registered your log line. It is stored separately. The second time is a part of the log line. It's connected to how you store logs inside qryn. (fluentBit, promtail or another ingester) Maybe there are some intelligent configurations to cut out time marks from initial log lines and send them as timestamp via the http protocol.

Show context button really depends on the initial logql request. I can't say what's wrong until I see the request. 
But I would open a debugger console of my browser on the "Networking" tab, then click "show context" button and look through the request it sends to Qryn. It can be corrupted sometimes.

**Comment by lmangani** [comment]
> @akvlad When I upgrade my grafana to 8.x, the problem is still exist.

Is it 8.5.x? We need all the details required to replicate this, since it seems to work fine for us and other users.

**Comment by wangchaoforever** [comment]
> > @akvlad When I upgrade my grafana to 8.x, the problem is still exist.
> 
> Is it 8.5.x? We need all the details required to replicate this, since it seems to work fine for us and other users.

yes，it's 8.5.6

**Comment by wangchaoforever** [comment]
@akvlad when I set only one label for ervery log, the "show context" worked fine. But it throw error like above when I set several labels.

**Comment by wangchaoforever** [comment]
> 

I tried again. I set 5 labels and the labels's fields are all not null,  the "show context" works ok. But when there are null filed labels in logs, "show context" will throw the above errors.

**Comment by lmangani** [comment]
@wangchaoforever could you show us a couple examples of labels with null values - are those intentionally generated?

**Comment by akvlad** [comment]
I see. Null valued tags are forbidden. I'll add a check with 400 response for that case.

**Comment by akvlad** [comment]
previous labels with null tags are broken, but after https://github.com/metrico/qryn/pull/178 all the inappropriate (non-string) tag values are stringified via the internal nodejs stringifier. 
Just a reminder that non-string tag values are invalid by the logQL specification. It's more like a workaround to stop loosing broken log entries.
