### ISSUE TITLE
Replication support

### ISSUE THREAD

**Issue by derlaft** [metrico/qryn#170]
Hi,

is replication support planned? 

In theory it should be possible to replace engines [here](https://github.com/metrico/qryn/blob/c81858b01d6a185e00e16aca096f6739a061de6c/lib/db/maintain/scripts.js) to be `Replicated*` and it should just work.

Documentation also mentions `distributed()`, but it's not clear how that's supposed to work

**Comment by derlaft** [comment]
Just noticed https://github.com/metrico/qryn/issues/62 - maybe it's a duplicate

**Comment by lmangani** [comment]
@derlaft you're correct, changing the engine should be all that's required - we know several users doing so, and we have a couple test setups on various cloud providers providing this out of the box and this could easily be turned into a setup preference if the users want it. Feel free to extend this thread with any suggestions.

**Comment by smmstf** [comment]
Hello, can you share the script to use to init replication please ?
I tried to replace the Engine as mentionned before but it didn't work. I saw issue #62 but it's not clear enough.

**Comment by derlaft** [comment]
>  But I didn't experiment with different replica and shard setups so any help is very welcome. It would be interesting to know how clickhouse distributes inserted data between different shards and how it reads data from. I'll check that today.

If you just use `Replicated` without any additional configuration:

* There will only be one shard, all the data should be present on all the nodes
* There will be no load balancing in terms of reads (for that, external load balancer is required)

From my understanding (might be incorrect here), `Distributed` is the next step, built on top of `Replicated`, which allows to implement some sharding and read distribution. I'm mainly interested in `Replicated` setup working, because it allows to achieve some fault tolerance in an extremely simple manner.

**Comment by akvlad** [comment]
@derlaft let's say I have 10 shards behind kubernetes of HAProxy & round robin. I added 1000 logs with 1000 INSERT requests.
Then I do `SELECT * FROM samples_v3`. Will it return all the 1000 rows or only the rows from the random shard (about 100)?

**Comment by akvlad** [comment]
@derlaft There can be a lot of shards with pure `Replicated` if I add some macros into config.xml
```
    <macros>
        <shard>unique_id_for_each_node_of_the_cluster_01</shard>
        <replica>example01-01-1</replica>
    </macros>
    <default_replica_path>/clickhouse/tables/{shard}/{database}/{table}</default_replica_path>
    <default_replica_name>{replica}</default_replica_name>
```

**Comment by lmangani** [comment]
Feel free to reopen if still interested for 3.x
