### ISSUE TITLE
Querying cloki metrics from prometheus (monitoring cloki service)

### ISSUE THREAD

**Issue by omartheironman** [metrico/qryn#173]
Is there is a /metrics url or an endpoint i can hit to fetch cloki metrics? inserts, queries, throughput etc?

**Comment by lmangani** [comment]
Yes, using the latest version and with the ENV `FASTIFY_METRICS` set a /metrics endpoint is published with API and memory statistics. This should of course be paired with the ClickHouse side statistics. Let us know if this helps!
