### ISSUE TITLE
[Question] generating fake old logs e.g. 6 months old

### ISSUE THREAD

**Issue by Skipper0707** [metrico/qryn#180]
Good day;

I need to test my log management stack's database query performance and in order to do so, I need to generate bulks of log messages that seem to be six months old.

I've come to understand that this could be possible using `cloki` HTTP API but I haven't been able to generate a valid Syslog RFC5424 log yet, also, I don't know if it's possible to forge fake timestamps using this method.

Is it possible to do so via the API?
If not is it possible to do so at all?
Can you bring some examples with forged timestamps to be pushed to Cloki API via the `curl` command?

Apologies in advance if anything's wrong with this question.

I really appreciate any help you can provide.

**Comment by Skipper0707** [comment]
UPDATE: I just found this piece of code in the wiki:

```bash
curl -i -XPOST -H "Content-Type: application/json" http://localhost:3100/loki/api/v1/push \
     --data '{"streams":[{"labels":"{\"__name__\":\"up\"}","entries":[{"timestamp":"2021-12-26T16:00:06.944Z", "line":"zzz"}]}]}'
```

apparently, this could do what I want, the question is since I'm a newbie, do I have to change anything like for example should I replace the `streams` part?

**Comment by lmangani** [comment]
Hi @Skipper0707 that's correct and it should work - make sure you use a label you can find. You could also use `vector` as a data generator in various formats then then script it to modify the timestamps. This is also useful to generate load tests against the stack using the loki sink. If needed I can share some examples.

**Comment by Skipper0707** [comment]
I would love it if you shared examples, also, thanks for the incredibly fast response.

**Comment by lmangani** [comment]
Here you go: https://gist.github.com/lmangani/01ef4dfe81dfa5f9ce63f947a1a46db8

**Comment by Skipper0707** [comment]
Thank you so much, both the `curl` method and `vector` method work just fine.

Lots of love your way and thank you for this amazing tool.

Closing issue since I got more than I wanted in the first place.
