### ISSUE TITLE
Whether queue support is required before cloki storage

### ISSUE THREAD

**Issue by ktpktr0** [metrico/qryn#184]
I used elk cluster before. It collects file logs from filebeat and stores them in Kafka. Logstash takes them out of Kafka and sends them to es

I want to know whether cloki needs Kafka queue support (especially when there is a large amount of logs)

**Comment by lmangani** [comment]
Hello @ktpktr0 

This is most definitely a popular use-case. Most logql compatible agents such as `vector` support this out of the box where you can have one (or many) instances reading the logs into a kafka sink and on the other hand, a receiver inserting them into qryn/cloki through the logql sink - just an example out of many I'd suggest vouching to keep things simple and robust without adding excessive weight into the application itself. Native support is on the roadmap but would not add any major benefits over `vector` + `kafka` doing the job in terms of delivery reliability.

Hope this helps!
