### ISSUE TITLE
[Question] How to stop seeing authentication information in container logs.

### ISSUE THREAD

**Issue by Skipper0707** [metrico/qryn#185]
Hello again and good day to you all;

After container creation via either `docker` or `podman` when you enter the command `podman logs qryn` or `docker logs qryn` you'd see the following output:

```json
> qryn@2.1.6 start /app
> node qryn.js

http://user:password@clickhouse:8123/?database=qyrn
show tables format JSON
http://user:password@clickhouse:8123/?database=qyrn
show tables format JSON
```

I tried to stop this behavior by changing the log level to `error` via the environment variable like `-e LOG_LEVEL="error"` but it still showed the authentication information. My question is how to stop this behavior?

**Comment by Skipper0707** [comment]
UPDATE:

I overrode the default entrypoint like below:

```bash
--entrypoint '["npm", "start", "--silent"]'
```
but it didn't change the above output so no joy.

**Comment by lmangani** [comment]
Hello @Skipper0707 looking into this, standby

**Comment by akvlad** [comment]
This line was removed during an overall logging review.
Please try v2.1.9.

**Comment by Skipper0707** [comment]
Sure will, thanks, will report back if it wasn't fixed.

Lots of love your way and appreciate the quick response and fix.

**Comment by lmangani** [comment]
Thanks for the report @Skipper0707 please reopen the issue if the fix lacks any aspect

**Comment by Skipper0707** [comment]
> Thanks for the report @Skipper0707 please reopen the issue if the fix lacks any aspect

The fix is perfect @lmangani.

Thanks for the absolutely quick response and fix.

Lots of love your way.

ps. I love this project and I'd love to contribute if needed, I will upload my resume so you'd see if there is anything I can do for y'all and your lovely project.

[Sina_Hosseini_Resume.pdf](https://github.com/metrico/qryn/files/9182068/Sina_Hosseini_Resume.pdf)
