### ISSUE TITLE
qryn managed alert doesn't get triggered.

### ISSUE THREAD

**Issue by Skipper0707** [metrico/qryn#189]
Hello again and good day to you.

I've created an alerting rule managed by `qryn` via [this guide](https://github.com/metrico/qryn/wiki/Ruler---Alerts#-qryn-ruler--alert-manager) and it looks like this:

![2](https://user-images.githubusercontent.com/71173136/182028758-ed6e224f-2552-48ae-9b86-4ba17d225ea4.png)

The problem is when I wanted to test it by manually inserting some logs to match the condition, the alert didn't change state from normal to pending and then firing even though when you click on the graph it shows that it has definitely matched the condition as it can be seen in the below picture:

![1](https://user-images.githubusercontent.com/71173136/182029109-136a3a98-fe1a-4da2-bc4a-5a3c7a5bed32.png)

I've tested some other expressions and log queries but the state doesn't change at all. As a matter of fact, the `normal` string in the first picture looks a bit weird since it doesn't have the green box around it.

In addition, I tried to see if the rule is actually inserted into qryn and it was:

```bash
curl -i -XGET -H "Content-Type: application/json" http://<SOME_IP>:<SOME_PORT>/api/prom/rules
HTTP/1.1 200 OK
vary: Origin
access-control-allow-origin: *
content-type: yaml
content-length: 288
Date: Sun, 31 Jul 2022 13:36:20 GMT
Connection: keep-alive
Keep-Alive: timeout=5

fake:
  - interval: 1s
    name: foobar
    rules:
      - alert: foo-app-error
        expr: rate({appname="foo-app"} |~ ".*error.*" [10s]) > 1
        for: 1m
        annotations:
          description: component foo is in an error state
          summary: foo error
        labels: {}
```

My Grafana notifications and routing are configured correctly, in fact, I tried the same expression but with a Grafana managed alerting rule and it worked just fine.

- Am I doing it right? Maybe I've misconfigured something (I'm open to sharing more information if needed.)
- Isn't there any other way to insert and add `qryn` managed alerting rules other than Grafana GUI and the API? (not related to this issue just asking).

**Comment by Dletta** [comment]
@Skipper0707 
Hi,

I just tried to reproduce the problem. A few things to note:

- Your are evaluating a 10s bucket every 1s for 1m. That may be causing the issue, have you tried increasing the evaluation to 10s in 1m? (In fact Grafana 9 will not let you use single-digit seconds for the interval)
- The way grafana evaluates, is this. Assuming 10 s for 1 m. It will wait for 10 seconds and then move to Pending state, if the value is still above the Threshold during the 10 seconds.

My rules have all fired as expected with the latest QRYN and latest Grafana. 

There is an error state when using a query as the evaluation, but it still fires the alert.
<img width="935" alt="Screen Shot 2022-08-01 at 1 33 59 PM" src="https://user-images.githubusercontent.com/5729042/182219682-2a0f0422-7480-49f6-8cd8-e5ecc1f036b4.png">

So from my testing it appears likely it is the query and the 'volume' of logs being too low, so the rule evaluates and see's the value drop back down and returns to Normal mode before it would move to pending. 

Try sending a regular interval of values above the threshold during the 10s interval time to make sure your rate and average is as expected for the Grafana Alert to actually go to pending and then fire.

**Comment by Skipper0707** [comment]
Hello @Dletta and thanks for taking the time to test and respond.

Thanks for explaining the evaluation process and Grafana 9's consideration.

Would you be so kind to keep on helping me? If yes, can you please tell me if the following rules are closer to your tests or not? In short, are they better?

```json
rate﻿(﻿{﻿appname﻿=﻿"foo-app"﻿}﻿ |~ ﻿".*error.*"﻿ ﻿[﻿1m﻿]﻿)﻿ > ﻿10

count_over_time﻿(﻿{﻿appname﻿=﻿"foo-app"﻿}﻿ |~ ﻿".*error.*"﻿ ﻿[﻿1m﻿]﻿)﻿ > ﻿10
```

**Comment by Skipper0707** [comment]
I'm gonna add a screenshot that may help you help me, when I click on the view button it says `no data` in the Query results section.

![image](https://user-images.githubusercontent.com/71173136/182344847-075b7087-9cb7-4150-952d-4d5ee2241f07.png)

This could indicate that I've misconfigured something.

**Comment by Dletta** [comment]
No problem at all.

If I understand correctly you want to see if you have *any* error messages
in your logs and be alerted?

Can you confirm your Grafana version and explain your goal. I think a 10s
interval and your rate query was fine, but if you look at the alert
definition you received back, it said it said Grafana had set it for you as
1s for 1m.

Once you tell me your Grafana version I'd be happy to recreate and check it
from my end.

**Comment by Skipper0707** [comment]
Thanks a lot, @Dletta, I appreciate you helping me, lots of love your way, and sorry for the late reply.

My Grafana version is v.2.0.9

**Comment by lmangani** [comment]
@Skipper0707 that's hardly possible: see [here](https://grafana.com/grafana/download). 
Our stack is compatible with Grafana 8.x and 9.x _(preferred)_

**Comment by Skipper0707** [comment]
@lmangani I apologize that was absolutely my bad, I meant to write v9.0.2

**Comment by Skipper0707** [comment]
@Dletta I have to mention that I'm using qryn v2.1.9 because of #185. Grafana is still v9.0.2.
