### ISSUE TITLE
Grafana Beta Search Support

### ISSUE THREAD

**Issue by Dletta** [metrico/qryn#194]
Following API is missing for Tempo Search (Grafana Beta Search)

Assuming a span with service.name = dummy-server and span name of "cache_lookup"

Search based on Service Name:
```js
{
  "method":"GET",
  "url":"/api/search?tags=%20service.name%3D%22dummy-server%22&limit=20&start=1661278983&end=1661282583"
}
```

Search based on Span Name:
```js
{
  "method":"GET",
  "url":"/api/search?tags=%20name%3D%22cache_lookup%22&limit=20&start=1661279205&end=1661282805"
}
```

Search by Tags is ends up in the same query as above, except with the keys inside tags. This may not be possible in the current format.

**Comment by lmangani** [comment]
@Dletta https://github.com/metrico/qryn/pull/195 ready for validation
