### ISSUE TITLE
Performance advice about label vs line filtering

### ISSUE THREAD

**Issue by dvillaume** [metrico/qryn#196]
Hello, 
firstly i must tell this seems really amazing like often with qxip + clickhouse.

i just have a question about performance optimization.

Scenario : 
-Storing  logs that contains correlation_id 
- ~ 500 lines with the same correlation_id
- The correlation_id will concerns logs of a 4 hour time range.
- 1 million different correlation_id/day
- LABELS_DAYS and SAMPLES_DAYS: 15

What would be the best for performances between :
- using few generic labels filtering + filtering high number of lines looking looking for the correlation_id. 
- using correlation_id as a label.

Do you have any advice about this ?
Regards

**Comment by akvlad** [comment]
Technically clickhouse can bear 15mln of different label sets. But I don't advice to have more then 10mln.
if corellation_id has a good random distribution you can do something like `corellation_id % 100000` or `crc16(corellation_id)` to reduce the cardinality.
So it can be corellation_id hash label + corellation_id filtering.
Or you first option is ok as well.
I don't advice to keep cardinality of more than 10mln of fingerprints in the database.

**Comment by lmangani** [comment]
Hey David - thanks for the kind words.

If the labels and the timerange can efficiently be used to reduce the set, assuming you'll query a subset of interest, I would not use the correlation_id as label since it can safely sit inside the message and be filtered at query time more efficiently without bloating the cardinality at all:
```
{ type="something", ipgroup="sbc12"} |= "correlation_id"
```

**Comment by dvillaume** [comment]
Thanks both of you for your answers, reactiveness and for your efforts about open-source tools.
