### ISSUE TITLE
Don't start in container

### ISSUE THREAD

**Issue by 1xtr** [metrico/qryn#205]
Very simple demo for try qryn:
docker container with CH already running in docker network.
I added container with `image: qxip/qryn:latest` and only one ENV like this
`CLICKHOUSE_SERVER=http://${CH_USER}:${CH_PASSWORD}@clickhouse-server:8123`

Container stop immediately if error:

```
{"level":50,"time":1661856775378,"pid":19,"hostname":"cloki","name":"qryn","err":"getaddrinfo ENOTFOUND http\nError: getaddrinfo ENOTFOUND http\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)","msg":"Error starting qryn"}
```

**Comment by lmangani** [comment]
Hello @1xtr 

Have you tried using our actual [ENV variables](https://qryn.metrico.in/#/env) to configure the process?

```
CLICKHOUSE_SERVER="clickhouse-server" \
CLICKHOUSE_AUTH="${CH_USER}:${CH_PASSWORD}" \
CLICKHOUSE_DB="qryn" \
qryn
```

Please refer to our full-blown example w/ all settings on our [qryn-oss-demo repo](https://github.com/metrico/qryn-oss-demo)
