### ISSUE TITLE
Opentelemetry traces enchancements

### ISSUE THREAD

**Issue by akvlad** [metrico/qryn#208]
# Current status
Opentelemetry traces are currently stored in the same table as logs. Searching by tags is provided by the same mechanism as logQL based searching. It has several disadvantages:
- looking for traceID is possible for the last hour only
- searching by the span duration is impossible as it needs full scan with JSON decoding

# Improvement request
Make a separate tables to save zipkin opentelemetry spans in and provide all the insert functionality.
The tables should support fast search by traceID, tags, duration. Search API should be compatible with Grafana Tempo.

**Comment by lmangani** [comment]
Successfully implemented! Thanks super @akvlad
