### ISSUE TITLE
use operator `like` instead of function `position()`

### ISSUE THREAD

**Issue by R-omk** [metrico/qryn#213]
https://github.com/metrico/qryn/blob/1c92c94/parser/registry/line_filter_operator_registry.js#L13

This may be useful in the future when using skip indexes.
https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#functions-support

related https://github.com/metrico/qryn/issues/100

**Comment by lmangani** [comment]
Thanks @R-omk another great point indeed 
Would you be interested in joining the project team? :)

**Comment by akvlad** [comment]
The fix was added to the beta release (2.1.58-beta)
Feel free to check.

**Comment by akvlad** [comment]
As far as the branch is merged and no complains, closing the issue.
