### ISSUE TITLE
Unreliable save data in Clickhouse

### ISSUE THREAD

**Issue by grimkirill** [metrico/qryn#221]
Each time when log ingester push new portion of data it expect 204 status code as a result of success processing and can retry request if any error. Right now qryn respond with succes rigth after ading this data into internal batch, this batch is afficient to be insterted into Clickhouse but does not provide any garanties about succes writes. Hence qryn losing data by its natire but this should be at least configurable or better more relialable by default by responding this success on push only after write.

**Comment by akvlad** [comment]
@grimkirill can you share the statistics? Like "During the night I pushed 1 000 000 log lines but it saved only 900 000"? 
Because I didn't see that effect during my local tests.

**Comment by lmangani** [comment]
@grimkirill this should not be the case but if you can reproduce this behaviour, please share any evidence (logs, errors, anything) and we'll gladly address any shortcomings

**Comment by lmangani** [comment]
Please reopen anytime if you have any data to share
