### ISSUE TITLE
Two rows of logs & two rows of labels per ONE fingerprint.

### ISSUE THREAD

**Issue by Skipper0707** [metrico/qryn#222]
Hello again;

We've been having some trouble querying logs in Grafana in which when querying a set of labels we'd have mixed-up results such as logs with two sets of labels but one of the sets of labels didn't exist in the log itself.

After digging deeper and querying directly from the Database I realized there are two rows of logs and two rows of labels for a single fingerprint and that could be the main cause of this issue.

```bash
container :) select * from samples_v3 where fingerprint = 3284143093;

SELECT *
FROM samples_v3
WHERE fingerprint = 3284143093

Query id: 8297eb90-6028-4631-8c3f-a4b41c7bafe5

┌─fingerprint─┬────────timestamp_ns─┬─value─┬─string─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│  3284143093 │ 1664706557745167016 │     0 │  {"appname":"FOO","level":"info","message":"BAR"}
 │
└─────────────┴─────────────────────┴───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌─fingerprint─┬────────timestamp_ns─┬─value─┬─string──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│  3284143093 │ 1665131094053029182 │     0 │  {"body":"HAY","level":"debug","pid":"<0.17575.1>","time":"2022-10-07T08:24:54.052272+00:00"}
 │
└─────────────┴─────────────────────┴───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

2 rows in set. Elapsed: 0.028 sec. Processed 10.42 million rows, 86.54 MB (372.46 million rows/s., 3.09 GB/s.)

container :) select labels from time_series where fingerprint = 3284143093;

SELECT labels
FROM time_series
WHERE fingerprint = 3284143093

Query id: 7f91f91f-34cc-4956-8491-1ab0021021f2

┌─labels─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ {"appname":"FOO","container_ip":"x.x.x.x","facility":"local0","host":"localhost","job":"syslog","level":"info","message":"BAR","pod_hostname":"mon,7fa1e727f1fe-infra","procid":"14"} │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌─labels─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ {"appname":"HAY_APP","body":"HAY]","container_ip":"x.x.x.x","facility":"daemon","host":"y.y.y.y","job":"syslog","level":"debug","pid":"<0.17575.1>","pod_hostname":"mon,7fa1e727f1fe-infra","procid":"665359"} │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

2 rows in set. Elapsed: 0.009 sec. Processed 76.91 thousand rows, 23.88 MB (8.51 million rows/s., 2.64 GB/s.)
```

I figure the purpose of `fingerprint` is to make the logs unique, after some search all of the mixed-up results in the Grafana have the same problems and other fingerprints have only one row of labels and log for them.

Any idea about this?
Thanks in advance.

**Comment by lmangani** [comment]
Sounds like a potential fingerprint collision. Further details might be required. @akvlad any theories?

**Comment by Skipper0707** [comment]
@lmangani  I'd love to provide more details, just tell me what you need.

I'm using `qryn:v2.1.9` due to the #185 and `clickhouse:v22.1.3.7`

**Comment by akvlad** [comment]
@Skipper0707 it seems you have a fingerprint collision.
You can enable a bigger fingerprint algo. Just specify `HASH=xxhash64` env var for qryn.

**Comment by Skipper0707** [comment]
@akvlad Thanks for the reply, changing the fingerprint algorithm via `HASH=xxhash64` solve my problem entirely Or should I test it for some time and report back?

**Comment by akvlad** [comment]
@Skipper0707 No. It's an OK tested feature. 
Can you send me the amount unique fingerprints you have?
Like `SELECT COUNT DISTINCT labels FROM time_series`?

**Comment by Skipper0707** [comment]
Of course @akvlad ;

```bash
container :) select count(distinct labels) from time_series

SELECT countDistinct(labels)
FROM time_series

Query id: 8058fa15-7d0e-4445-98a9-8f7d4fc7026b

┌─uniqExact(labels)─┐
│            695057 │
└───────────────────┘

1 rows in set. Elapsed: 0.340 sec. Processed 696.00 thousand rows, 220.19 MB (2.05 million rows/s., 647.09 MB/s.)

container :) select count(distinct fingerprint) from time_series

SELECT countDistinct(fingerprint)
FROM time_series

Query id: 2032db79-5171-41f7-83ce-bbd3e4feeadc

┌─uniqExact(fingerprint)─┐
│                 695056 │
└────────────────────────┘

1 rows in set. Elapsed: 0.087 sec. Processed 696.08 thousand rows, 5.57 MB (8.01 million rows/s., 64.04 MB/s.)
```

**Comment by akvlad** [comment]
@Skipper0707 So 695K. Does qrynJS work ok fast for this amount of labels? 
Like speed of grafana load, grafana autocomplete?

**Comment by Skipper0707** [comment]
@akvlad I could say it's fast enough, it takes about 3 seconds to load the first 1000 lines of log of `job=syslog` which basically means all of my log labels altogether, selecting distinct and specific labels such as `appname` and `level` adds another 2 seconds to the time.

I have to mention I've made some optimization to the Clickhouse reducing the resource consumption, so if it's slower than your environment it could be because of optimizations too.

**Comment by lmangani** [comment]
@Skipper0707 if you separate writing and reading in different qryn instances or simply multiply the number of instance and balance between them you can probably boost the performance significantly for a very low overhead

**Comment by Skipper0707** [comment]
@lmangani thanks for suggesting that, it sounds interesting. I will certainly try that and report back.

It might take some time due to our priorities but I will definitely try it.

**Comment by Skipper0707** [comment]
@lmangani @akvlad I'm sorry if I didn't open a new issue/question but I kind of want to take advantage of your kindness and ask for help regarding calculating `logs per second`, I've been trying to calculate my log management `logs per second` to find a relationship between resource consumption and `logs per second`. Is there any approach or method that you would suggest to calculate `logs per second` as accurate as possible?

**Comment by akvlad** [comment]
@Skipper0707 if you have a common label name for all the labels you can use `count_over_time` or `rate` to calculate how many you produce per second.
But the real ingestion rate is not implemented.

**Comment by Skipper0707** [comment]
@akvlad Thanks for the absolutely quick reply, as a matter of fact, I do have the `job="syslog"` label and can in fact perform your suggestion.

Thanks again.

**Comment by lmangani** [comment]
True ingestion rate would need exposing metrics from the ingestion layer. It's in the roadmap

**Comment by Skipper0707** [comment]
@lmangani Thanks for the quick reply.

That's actually great to hear. I'm looking forward to having those metrics available, they would make my job a lot easier. I'm `watch`ing the repo so I'd probably get a notification when they're implemented.

In the meantime, I'm going to use dear @akvlad 's suggestion to have an estimate of our ingestion rate.

**Comment by lmangani** [comment]
Let us know if the collision is resolved and feel free to reopen an issue anytime if needed

**Comment by Skipper0707** [comment]
Sure thing I will monitor it for a couple of days and report back.

Thanks for all of your help.

**Comment by Skipper0707** [comment]
The fingerprint collision seems to be resolved after one day of monitoring, I will reopen this issue if another occurrence happened.

In addition, your suggestion to separate writing and reading in different instances of `qryn` did in fact boos the performance noticibly.

Thanks for all of your help,
lots of love your way.

closing for now...
