### ISSUE TITLE
Labels/Entries ingestion API Format

### ISSUE THREAD

**Issue by Dletta** [metrico/qryn#228]
#### Current Behavior

When using the following format of insert:
```javascript
{
    streams: [
      {
        labels: '{ http="writer", filterNumber="6" }',
        entries: [
          {
            ts: '2022-04-14T17:35:16.357Z',
            line: logstring
          }
        ]
      }
    ]
  }
 ```
 
 We get a code 200 with Status Code 500.
 
#### Expected Behavior

Ingestion should work with this insert format.

**Comment by akvlad** [comment]
@Dletta can you validate your input in this site? https://jsonformatter.curiousconcept.com/ it doesn't look like a valid json input.

**Comment by Dletta** [comment]
Correct, it is not json, rather the object representing the format in question.

**Comment by akvlad** [comment]
@Dletta I can't reproduce it with the code snippet you have provided. Please provide the certain curl request.

**Comment by lmangani** [comment]
@Dletta can this issue be closed?
