### ISSUE TITLE
node OOM when traceID with too many Span

### ISSUE THREAD

**Issue by Cluas** [metrico/qryn#231]
```bash
<--- Last few GCs --->

[19:0x4f7ef50]   123121 ms: Mark-sweep (reduce) 510.8 (521.1) -> 510.1 (521.1) MB, 1516.5 / 0.0 ms  (+ 108.8 ms in 22 steps since start of marking, biggest step 79.0 ms, walltime since start of marking 1715 ms) (average mu = 0.216, current mu = 0.196) all[19:0x4f7ef50]   125370 ms: Mark-sweep (reduce) 511.3 (521.1) -> 510.4 (521.4) MB, 1870.1 / 0.0 ms  (+ 89.1 ms in 15 steps since start of marking, biggest step 74.7 ms, walltime since start of marking 1965 ms) (average mu = 0.170, current mu = 0.129) allo

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb06730 node::Abort() [node]
 2: 0xa1b6d0  [node]
 3: 0xce1dd0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xce2177 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xe997e5  [node]
 6: 0xe9a2c6  [node]
 7: 0xea87ee  [node]
 8: 0xea9230 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xeac1ae v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xe6d422 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [node]
11: 0xe65a34 v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawWithImmortalMap(int, v8::internal::AllocationType, v8::internal::Map, v8::internal::AllocationAlignment) [node]
12: 0xe67740 v8::internal::FactoryBase<v8::internal::Factory>::NewRawOneByteString(int, v8::internal::AllocationType) [node]
13: 0x10f8aa8 v8::internal::String::SlowFlatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal::ConsString>, v8::internal::AllocationType) [node]
14: 0x11d4273 v8::internal::RegExpImpl::IrregexpExec(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSRegExp>, v8::internal::Handle<v8::internal::String>, int, v8::internal::Handle<v8::internal::RegExpMatchInfo>, v8::internal::RegExp::ExecQuirks) [node]
15: 0x11f944b v8::internal::Runtime_RegExpExecTreatMatchAtEndAsFailure(int, unsigned long*, v8::internal::Isolate*) [node]
16: 0x15da0d9  [node]
Aborted (core dumped)
```

trace_id(hex): 171fb25c24c382c8

**Comment by lmangani** [comment]
@Cluas assuming the docker container can use as much memory as it wants to, did you configure your nodejs process to use all the memory it wants? By default the limits are very low. 
```
--max-old-space-size=4096
```
Alternatively just spawn more instances and distribute the load between them.

**Comment by Cluas** [comment]
> @Cluas assuming the docker container can use as much memory as it wants to, did you configure your nodejs process to use all the memory it wants? By default the limits are very low.
> 
> ```
> --max-old-space-size=4096
> ```
> 
> In a compose use ENVs
> 
> ```
> NODE_OPTIONS="--max-old-space-size=4096"
> ```
> 
> Alternatively just spawn more instances and distribute the load between them.

I changed this configuration and confirmed that this is not the problem, no matter how large I set it, the OOM will appear

**Comment by lmangani** [comment]
Then the container memory is smaller than the parameter. Hardcode the memory to be the same for the container and the NodeJS process. This is not a qryn issue but rather a NodeJS in Docker question. Let's find the sweet spot.

With compose 3 you can specify container limits. Something as follows might do the trick:

```
NODE_OPTIONS="--max-old-space-size=4096"
deploy:
  resources:
    limits:
      memory: 4096M
    reservations:
      memory: 4096M
```

**Comment by Cluas** [comment]
I found the reason, indeed the amount of data is too large, there is a traceID associated with 1499201 span...

**Comment by lmangani** [comment]
> I found the reason, indeed the amount of data is too large, there is a traceID associated with 1499201 span...

Could you explain this further? I do not understand.

**Comment by Cluas** [comment]
> > I found the reason, indeed the amount of data is too large, there is a traceID associated with 1499201 span...
> 
> Could you explain this further? I do not understand.

A service that performs a bulk request, using the same trace context, and generates 1499201 associated trace span.

**Comment by Cluas** [comment]
Can we limit this, I don't want the whole qryn service to be unavailable because of a faulty traceID. @lmangani

**Comment by Cluas** [comment]
> Unfortunately we can do nothing about this problem. Making readable traces is completely on you. The only thing I can do is to provide the limit... well, top 2000 first spans in the trace. next spans will be unable to read.

Can be used as an environment variable configuration items, so that you can better protect the service, the user reported behavior we can not control😂, only try to minimize the impact.

**Comment by lmangani** [comment]
@Cluas good point but the system is not designed to police input and assumes agents sanitize output. If this is a bug (we badly interpret a valid object) we should open a dedicated issue and fix it. If the object is bad.... its the agent's fault to fix

**Comment by Cluas** [comment]
> @Cluas good point but the system is not designed to police input and assumes agents sanitize output. If this is a bug (we badly interpret a valid object) we should open a dedicated issue and fix it. If the object is bad.... its the agent's fault to fix
> 
> If you have more details, we'll try help find a good solution or safe workaround.

This is an occasional case, we can just take protective measures, such as reporting an error to tell the user that the data associated with the traceID is too large, or just truncate some of the returned data, any ideas? @lmangani

**Comment by lmangani** [comment]
Let's brainstorm. Edge first - Does the sending agent support bulk limits?

**Comment by akvlad** [comment]
50MB / sec is the limit for now.

But we can't measure how many spans are in the trace at the time a client is sending a new one.

**Comment by akvlad** [comment]
We can of course measure it afterwards and provide an alert about that.
"Your trace `123EF` is too large, we dropped some spans from it, sorry"

**Comment by akvlad** [comment]
@Cluas I have added the limit for reading spans. Please check against one of your giant traces.
https://github.com/metrico/qryn/pull/234

I'm thinking about the alerts for big traces.

**Comment by akvlad** [comment]
2000 spans limit is merged.

**Comment by Cluas** [comment]
> 2000 spans limit is merged.

ok, I will try. thanks!
