### ISSUE TITLE
[Question] How to configure Qryn's Alert destination?

### ISSUE THREAD

**Issue by Skipper0707** [metrico/qryn#233]
Hello again;

I have a Qryn-managed alerting rule that works perfectly fine thanks to the guidance given in #189 like below:

![image](https://user-images.githubusercontent.com/71173136/197324296-1cd3bb9d-f261-4382-8ec8-575b224a7748.png)

However, I don't know how to configure the alert destination and tell either Qryn or Alertmanager to send this alert to my destination which is a Telegram Chat.

I have tried to configure notification policies using the tag `div=zyrrus`  like below:

![image](https://user-images.githubusercontent.com/71173136/197324351-012e91da-4f91-425e-a253-259967328adb.png)

![image](https://user-images.githubusercontent.com/71173136/197324379-b3b96cb1-1a33-4b52-8b3d-c6de3d800315.png)

But it didn't work.

It's possible to configure Grafana Loki alerts destination like the below:

![image](https://user-images.githubusercontent.com/71173136/197324427-a32fbff6-2f11-407b-8820-62dd07987485.png)

However, I don't know how to achieve this with Qryn.

Any help is appreciated.

**Comment by akvlad** [comment]
We don't have ring kvstore.
We don't have any local storage except clickhouse.

In order to configure the tlg output you have to install an instance of Alertmanager https://prometheus.io/docs/alerting/latest/alertmanager/ and to configure it to send alerts to telegram.

Then you should configure qryn to use the alertmanager instance you created: `ALERTMAN_URL=http://my_alertmanager_url:1234`

**Comment by akvlad** [comment]
I see the state of an alert as `firing`. It means that it sends something to alertmanager. Maybe you have some misconfiguration in there.
Qryn has only one configuration option: `ALERTMAN_URL`

**Comment by Skipper0707** [comment]
Thanks, @akvlad, that solves my problem regarding the Alertmanager configurations. I already do have an instance of Alertmanager the problem was I wasn't able to find Qyrn side's configurations regarding Alertmanager in the wiki nor the documentation [here](https://qryn.metrico.in/#/env).
