### ISSUE TITLE
lokiAPI can't support request body compress

### ISSUE THREAD

**Issue by zly-app** [metrico/qryn#239]
if headers has `Content-Type: application/json` and body use gzip compress. 
then request got this error.

API: `/loki/api/v1/push`

```text
{"statusCode":500,"error":"Internal Server Error","message":"Internal Server Error"}
```

but not use compress is Perfect operation

**Comment by zly-app** [comment]
log

```text
{"level":50,"time":1667811458684,"pid":19,"hostname":"26f783e43629","name":"qryn","reqId":"req-5y","err":"Unexpected token \u001f in JSON at position 0\nSyntaxError: Unexpected token \u001f in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at lokiPushJSONParser (/app/parsers.js:27:17)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Parser.fn (/app/parsers.js:237:12)","msg":"Unexpected token \u001f in JSON at position 0"}
```

**Comment by lmangani** [comment]
How are you sending data? Did you set `Content-Encoding: gzip` in the request?

**Comment by akvlad** [comment]
Yeah. GZIP demands `Content-Encoding` as described here https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding . I can test and implement if needed.

**Comment by lmangani** [comment]
We could use the Fastify handlers globally or selectively to act based on headers
WIP https://github.com/metrico/qryn/pull/265

**Comment by qxip-push** [comment]
@zly-app could you give https://github.com/metrico/qryn/pull/265 a try? This should fix your reported issue.

**Comment by akvlad** [comment]
@zly-app, https://github.com/metrico/qryn/tree/global-decompression
seems to have a full-weight solution for compression/decompression. Feel free to check.

**Comment by akvlad** [comment]
The branch was added to the beta release (2.1.58-beta)

**Comment by Dletta** [comment]
This was tested and merged, Closing the issue as resolved.
