### ISSUE TITLE
Documentation: minimal required version of clickhouse

### ISSUE THREAD

**Issue by MalKeshar** [metrico/qryn#243]
I'm fail to find minimal required version of clickhouse, which is compatible with qryn.

It is not possible to run docker-qryn(v2.1.42) with clickhouse<21.6 due to https://github.com/ClickHouse/ClickHouse/issues/20865.
This fix was added only in 21.6. I think it good to mention that qryn requires clickhouse>=21.6 somewhere.

**Comment by lmangani** [comment]
@MalKeshar great question! We're trying to assemble a compatibility table - will prioritize this in the docs!

In general terms, the latest LTS is the ideal target as we do use the latest features available.

**Comment by lmangani** [comment]
Feel free to comment and/or reopen if needed & thanks for the suggestion!
