### ISSUE TITLE
Docs: project roadmap page

### ISSUE THREAD

**Issue by MalKeshar** [metrico/qryn#248]
First of all, thank you for open-sourcing your very promising project!

I found  project roadmap in your presentation dated by 10.2021
https://www.slideshare.net/Altinity/cloki-like-loki-but-for-clickhouse
but I fail to find current status of it. Do you have page with roadmap, which can you share?

labels: question, docs

**Comment by lmangani** [comment]
Feel free to reopen if still interested for 3.x
