### ISSUE TITLE
allow flag for disable schema creation/allignment

### ISSUE THREAD

**Issue by vbichov** [metrico/qryn#251]
in some cases, it should be possible to provision the database schema outside the application 
it may be due to secutiry reasons or for trying out some experimental features that clickouse provides

it is granted that users that enable this flag should be familiar with the shcema and it's usage

**Comment by akvlad** [comment]
Fixed in 2.1.48.
Please use `OMIT_CREATE_TABLES=1` env var to omit tables creation.

**Comment by lmangani** [comment]
Documented at https://qryn.metrico.in/#/env
