### ISSUE TITLE
Different time in aggregated data between loki and qryn

### ISSUE THREAD

**Issue by MalKeshar** [metrico/qryn#262]
I start to compare results between loki and qryn on the same dataset. Well I'm not sure the dataset exactly the same I just send the same data via vector to loki and qryn uplinks. So at some point I found the difference in calculated data between them. Further investigation shows me that cloki and qryn even use different approaches while aggregating data. The same query (instant)
```
count_over_time({tag_log_name="zabbix-web-error",tag_log_level=~"ERROR",tag_host_dns=~"^(webslave|webmaster).+$"}[$__range])
```

gave me different results not only in data, but the time of aggregated data was different.

While loki shows current time in result subset, qryn shows hour back rounded by hour. 

Both hosts use the same TZ, ntp is on and the time is the same. loki&qryn run in the docker containers.

```
docker exec -ti cont "date"
```

shows the same UTC zone and the same time

Please take a look on screenshot. Columns except "Time" are hidden by me

![Screenshot from 2022-11-24 19-24-12](https://user-images.githubusercontent.com/13730780/203831849-2a92d2cf-fd98-4cae-84ca-73e85e9fb8eb.png)

**Comment by MalKeshar** [comment]
I don't know if time diff is the reason for different results in calculations. I'm not sure I will have a time to take a deeper look in this issue. Probably I have to switch to using loki in my tests in the near future.

**Comment by akvlad** [comment]
Qryn and Loki use different aggregation algorithms.
Loki uses time window.
Qryn rounds to the duration you specify in `[]`. (Like GROUP BY in SQL).  It is quite descriptive if you compare range queries.
This is considered due to performance issues.
I'll recheck instant queries results, but we do not plan to use window functions in aggregations.
