### ISSUE TITLE
FASTIFY_BODYLIMIT is not found in the code

### ISSUE THREAD

**Issue by vbichov** [metrico/qryn#273]
tried increasing request body size and found this [issue](https://github.com/metrico/qryn/issues/69) with the above flag mentioned in the docs

but I can't seem to find any mentions of that flag (FASTIFY_BODYLIMIT) in the code.

What am I missing?

**Comment by lmangani** [comment]
Thanks @vbichov indeed it seems a recent refactor left this ENV mid-air in new releases. Coming up in a new PR next.

**Comment by lmangani** [comment]
Restored in [v2.1.56](https://github.com/metrico/qryn/commit/c5b4030d014fb0c9a5c3c4158ab49462dc0b9cb0)

Thanks for the report @vbichov
