### ISSUE TITLE
Change alter table query storagePolicy to storage_policy

### ISSUE THREAD

**Issue by mikhno-s** [metrico/qryn#274]
https://github.com/metrico/qryn/blob/43821d9408f0eaa878f10bb2ebff28c34e1e62d1/lib/db/maintain/index.js#L106

The right setting is `storage_policy` not `storagePolicy`

**Comment by mikhno-s** [comment]
https://github.com/metrico/qryn/pull/275

**Comment by mikhno-s** [comment]
Героям Слава! 🇺🇦

**Comment by mikhno-s** [comment]
Merged fix, thanks for the rapid feedback!

**Comment by lmangani** [comment]
Thanks for the PR, merged and released!
