### ISSUE TITLE
Label Endpoint empty but query_range returns values

### ISSUE THREAD

**Issue by megalan247** [metrico/qryn#293]
Hi there,

Thank you for working on this project! It will be super helpful for us to ingest historical logs, as Loki is really bad at this :D

However, we have found that for some reason, when adding logs manually via curl they would appear when manually querying in /query_range, but the labels would not appear when querying the /label endpoint.

Steps to reproduce:

Using the latest docker-compose file, enter a log line with the below curl

```
curl -i -XPOST -H "Content-Type: application/json" IPADDR:3100/loki/api/v1/push \
     --data '{"streams":[{"stream":{"type":"test"},"values":[["1672580991617000000", "hello qryn"]]}]}'
```

Then when querying the endpoint

```
/loki/api/v1/label?start=1672527600000000000&end=1675292400000000000
```
it returns
```json
{
"status": "success",
"data": [ ]
}
```
Showing no labels in this timeframe... However then when querying the query_range endpoint
```
loki/api/v1/query_range?query=%7Btype%3D"test"%7D&limit=100&start=1672527600000000000&end=1675292400000000000&step=1&direction=forward
```
it returns the expected values
```
{"status":"success", "data":{ "resultType": "streams", "result": [{"stream":{"type":"test"},"values":[["1672580991617000000","hello qryn"]]}]}}
```

The start and the end params of each of these requests is the same. Is this expected behavior? Interestingly, when drastically increasing the end= time to 1775292400000000000, the labels appear in the response.

**Comment by lmangani** [comment]
Thanks for your report and for the kind words @megalan247 
Very interesting and super valid use case. We'll reproduce and find the root cause and fix.

**Comment by akvlad** [comment]
Hello @megalan247 .  I see the problem. Please don't use `start=1672527600000000000&end=1675292400000000000` in the `/labels` request for now. 
I'll fix it tomorrow.

**Comment by akvlad** [comment]
@megalan247 have a solution for you in `v2.2.12`. Should work for your case.

**Comment by megalan247** [comment]
Hi there, looks like it is working now! Thanks for the quick response :)
