### ISSUE TITLE
topk function not working

### ISSUE THREAD

**Issue by timansky** [metrico/qryn#299]
Hi
I've tried to use topk function but with no success(
Query: `topk(5,sum(count_over_time({log_type="vector"}[1m])) by (type))`
Response ` {"statusCode":400,"error":"Bad Request","message":"invalid request"}`

Same query with loki works as expected

**Comment by lmangani** [comment]
Thanks for the report @timansky could you confirm your qryn-js and clickhouse versions?

**Comment by timansky** [comment]
clickhouse: 22.9.7.34
qryn: 2.2.5

**Comment by lmangani** [comment]
@timansky confirmed, and apologies - this was left behind and/or broken at some point on the way here - a fix for this issue implementing topk/bottomk will be available in the next releases

**Comment by akvlad** [comment]
@timansky we have an experimental solution in the branch https://github.com/metrico/qryn/pull/308
It will be merged after some extra work.
Feel free to use.

**Comment by akvlad** [comment]
topk function is in release now. `v2.2.17`, feel free to use.
