### ISSUE TITLE
quantile_over_time not working

### ISSUE THREAD

**Issue by anolek** [metrico/qryn#301]
Hi

I tried to use qryn instead of loki but quantile_over_time function doesn't work
``quantile_over_time(0.95, {job="test-syslog"} | json | unwrap systime [1m]) by (process)``
Return 
``{"statusCode":500,"error":"Internal Server Error ","message":"QrynBadRequest"}``

Clickhouse Version: 22.9.1
Qryn Version: 2.2.14

Thanks !

**Comment by lmangani** [comment]
This `quantile_over_time` function is currently [unsupported](https://github.com/metrico/qryn/wiki/LogQL-Supported-Queries) in the qryn-js version as per docs. Let's check how far it is on the roadmap and confirm that next.

**Comment by akvlad** [comment]
quantile_over_time function is released now. `v2.2.17`, feel free to use.

**Comment by akvlad** [comment]
Close the issue as resolved.
Please reopen if needed.
