### ISSUE TITLE
sum over count with json parsed field

### ISSUE THREAD

**Issue by timansky** [metrico/qryn#305]
Having a problem with query
```sum(
  count_over_time(
  {
    foo="bar"
  }
  | json
  [1m])
) by (json_exported_field)```

returns null or some times return not full result (last n minute where request time range is bigger than n) 

clickhouse: 22.9.7.34
qryn: 2.2.14

**Comment by timansky** [comment]
<img width="1666" alt="sum_by_json_field" src="https://user-images.githubusercontent.com/1217278/222351010-40a4a800-dca8-44c0-bedd-a6de0f1f7e14.png">
<img width="1668" alt="sum" src="https://user-images.githubusercontent.com/1217278/222351039-43ae83d0-faa6-4339-bc96-23febff71939.png">

**Comment by akvlad** [comment]
Thanks for the issue raise, @timansky .
Working on it. 
Even after this issue is resolved parameterless `| json` operator may appear too slow for the data volume you have. Please use `| json level_name="level.name"` instead. It works now and it's much faster than the parameterless one.

**Comment by timansky** [comment]
yes, query with specifying the field is working as expected

```
sum(
    count_over_time(
  {
    foo="bar"
  }
  | json json_exported_field ="json_exported_field"
  [$__interval])
) by (json_exported_field)
```

**Comment by akvlad** [comment]
Fixed. Json with no params should work since v2.2.16.

**Comment by akvlad** [comment]
Close the issue as resolved.
Please reopen if needed.
