### ISSUE TITLE
[FeatureRequest] Matrix support for Charting in Grafana Explore

### ISSUE THREAD

**Issue by timansky** [metrico/qryn#306]
There is a difference between loki and qryn query result when it is made in Grafana Explore.
By default loki returns matrix, but qryn returns stream.

Matrix is used to visualise log volume by error level.

<img width="1661" alt="qryn" src="https://user-images.githubusercontent.com/1217278/222357444-100127b0-8ab2-4322-9063-c12d661cf02c.png">
<img width="1671" alt="loki" src="https://user-images.githubusercontent.com/1217278/222357471-df65b496-4184-4f0a-8d61-3472034ccadb.png">

Matrix is already supported as i  see in #18

**Comment by akvlad** [comment]
What is the version of grafana you use? Because in grafana v9.1.0-beta.1 I see this.
https://nimb.ws/4BMtdx

**Comment by akvlad** [comment]
![screenshot-localhost_3000-2023 03 02-11_06_26](https://user-images.githubusercontent.com/2798590/222383670-c844e345-5827-4fdb-a601-68b8d9db369c.png)

**Comment by akvlad** [comment]
grafana v9.4.2: 

![screenshot-localhost_3000-2023 03 02-11_15_01](https://user-images.githubusercontent.com/2798590/222384742-bd47b1cb-410c-4225-afc1-649542bdaf54.png)

**Comment by timansky** [comment]
Grafana v8.5.13, but i've tried latest 9.4.2 and result is same

loki
<img width="1660" alt="loki" src="https://user-images.githubusercontent.com/1217278/222392409-903baad3-86c7-4f1d-b2af-d136b8b5d7de.png">
qryn
<img width="875" alt="qryn" src="https://user-images.githubusercontent.com/1217278/222392441-a864cdf8-c2cf-46c2-8dde-730501025e38.png">

**Comment by akvlad** [comment]
I don't know without looking into the logs you have.

Do you expose log levels as labels? Can you check `{dc="alakt", level="error"}`  in qryn? The volume chart does nothing but runs a query `sum by (level) (count_over_time({dc="alakt"}[1m]))` . Please check it as well.

**Comment by timansky** [comment]
My mistake, found miss config in log sending
