### ISSUE TITLE
Version doesn't refer to a docker image tag. 

### ISSUE THREAD

**Issue by timansky** [metrico/qryn#309]
There is something wrong in actions pipeline
version and image tag are not equal

```
❯ docker run --rm -ti qxip/qryn:v2.2.17

> qryn@2.2.16 start
> node qryn.js
```

**Comment by Dletta** [comment]
Confirmed.
Running version lags one iteration behind the tag.
Current Tag v2.3.2, show 2.3.1 inside.

**Comment by lmangani** [comment]
Permanently Resolved in 3.x
