### ISSUE TITLE
Select series which does not contains label

### ISSUE THREAD

**Issue by timansky** [metrico/qryn#325]
Faced with an issue with labels.
The case is to select all series which does not contain specific label.
Loki syntax: 
```
{
  label_foo="bar",
  label_bar=""
}
```
Query will return all matched series which does not contain `label_bar`. Qryn returns nothing because label must contain something.

**Comment by lmangani** [comment]
I am not sure we store empty labels at all. Could you confirm with some examples for the labels of a matching object?

**Comment by timansky** [comment]
The issue is not that store empty labels, loki also does not store empty labels. Empty label means that this label must not exist in timeseries 

For example we have next series with tuple labels:
```
{label_1="foo"}
{label_1="foo", label_2="bar"}
{label_2="foo", label_3="bar"}
```

Query`{label_1="foo", label_2=""}` must return only series with label `{label_1="foo"}`, and not return series which has lable_2 in metadata

**Comment by timansky** [comment]
In other words, i want to select all series which does not contain specific label

**Comment by timansky** [comment]
Same technique  Loki uses for parsing json parsing error exclusion.

```{label_foo="bar"} | json | __error__=""```

**Comment by Dletta** [comment]
I am seeing the described expected behavior with qryn v2.3.2.

```
{label_1="foo"}
{label_1="foo", label_2="bar"}
{label_2="foo", label_3="bar"}
```

searching ```{label_1="foo", label_2=""}``` I do not see any series that has label_2 inside the series.

**Comment by timansky** [comment]
yes, 
CHPROXY_VERSION=v1.21.0
QRYN_VERSION=v2.3.2
CLICKHOUSE_VERSION: 22.9.7.34

**Comment by Dletta** [comment]
Can you confirm it works now?
I did confirm it worked for me in the above version as expected.

**Comment by lmangani** [comment]
Closing as completed. Please reopen in case of issues.
