### ISSUE TITLE
Feature Request: sum aggregation in prom2logql transpiler

### ISSUE THREAD

**Issue by rickysaltzer** [metrico/qryn#327]
Seems like I can't do simple aggregation operations using the Grafana + Prom plugin. 

**Query:**
```
sum(flink_taskmanager_job_task_numRecordsIn{job_name="flink_job_test"})
```

**Error:**
```
Expected [ or 'SYNTAX' ] @1:0 encountered 'sum({'.
sum({ __name__="flink_taskmanager_job_task_numRecordsIn", job_name="flink_job_test"} | unwrap_value [1m])
{"level":50,"time":1683836374683,"pid":19,"hostname":"68597ad42fb1","name":"qryn","reqId":"req-3ta","err":"invalid request\nBad Request: invalid request\n    at Object.module.exports.transpile (/app/parser/transpiler.js:94:11)\n    at Object.scanFingerprints (/app/lib/db/clickhouse.js:227:29)\n    at Object.handler (/app/lib/handlers/prom_query_range.js:38:33)\n    at Object.routeOptions.handler (/app/node_modules/@fastify/websocket/index.js:143:24)\n    at preHandlerCallback (/app/node_modules/fastify/lib/handleRequest.js:128:37)\n    at preValidationCallback (/app/node_modules/fastify/lib/handleRequest.js:112:5)\n    at handler (/app/node_modules/fastify/lib/handleRequest.js:76:7)\n    at handleRequest (/app/node_modules/fastify/lib/handleRequest.js:24:5)\n    at next (/app/node_modules/fastify/lib/route.js:545:7)\n    at Object.preParsing (/app/node_modules/@fastify/compress/index.js:299:14)","msg":"invalid request"}
```

**Comment by lmangani** [comment]
Hi @rickysaltzer thanks for the report. As the [docs specify](https://qryn.metrico.in/#/support) qryn-js supports full ingestion of prometheus formats, but only supports transpiling a very small subset of promql to logql. The qryn-go version running qryn.cloud supports the full prometheus query language and much of the APIs.

This said: I'll add the above query to the prom2logql validation to confirm whether this can be supported.

**Comment by rickysaltzer** [comment]
oh no, that's really unfortunate...was really hoping to use Qryn with our ClickHouse Cloud cluster 😄

**Comment by lmangani** [comment]
Sorry! JS can't cut that deep. We'll keep adding all the promql queries the js engine can support and we'll release qryn-go with the full promql features as soon as we get our development fully founded, for now its just a cloud feature (your can connect it to your own cluster with the BYOC option)

**Comment by rickysaltzer** [comment]
Totally understand! Perhaps not the platform to ask, but I was wondering why the the BYOC option is over 2x the price of using your storage.

**Comment by lmangani** [comment]
That's a very good point! @rickysaltzer its because the BYOC options are unmetered and basically dedicated w/ ingress+egress costs included, while the shared option is using our own storage and bandwidth costs are for ingestion only. We'd be happy to take all the feedback you have on the subject as we try make the pricing as fair and appealing as possible - if you'd like to talk, just sign up for a demo and we'll reach out!

**Comment by gabomgp4** [comment]
Support for promql changed in last months?

**Comment by lmangani** [comment]
Hello @gabomgp4 
- qryn-js/node: promql is still based on prom2logql, a few more functions were added
- qryn-cloud/go has full promql transpiling support

We're working on a new major version which might change the above to some extent, but we're still mid-development
