### ISSUE TITLE
Incorrect results from prometheus query when no label is provided

### ISSUE THREAD

**Issue by nchopra** [metrico/qryn#333]
Hi, qryn returns incorrect results from prom queries when you do not provide a label. For example 
* `grafana_stat_totals_admins` returns 0.0167 (incorrect, no of admins is 1)
* `grafana_stat_totals_admins{job="grafana"}` returns 1 (correct)
screenshots below show the error via grafana
Am I missing something here?

<img width="1241" alt="cs 2023-07-07 at 14 44 50@2x" src="https://github.com/metrico/qryn/assets/1182597/ddcc6744-f2c8-4366-8309-24ea0d74689c">
<img width="1248" alt="cs 2023-07-07 at 14 45 09@2x" src="https://github.com/metrico/qryn/assets/1182597/8035c221-4321-4815-81b4-85a51508cc81">

**Comment by lmangani** [comment]
Thanks for the report @nchopra it's much appreciated!
The prometheus queries in qryn-js are actually transpiled to logql metric queries, so there are several limitations compared to the qryn.cloud service. We'll replicate this and provide some updates!

**Comment by nchopra** [comment]
Thanks @lmangani for looking into this!
I did read in the readme that there are limitations but this issue seemed to be too elementary so I suspect a bug unless I am missing something on my setup.

**Comment by lmangani** [comment]
@nchopra completely agree, this should work and its not a special case. We'll find a fix next.

**Comment by lmangani** [comment]
So far I cannot reproduce this. Could you show me a few rows from your series?

**Comment by nchopra** [comment]
All show the same value.
I did check in clickhouse, the values there are correct as expected.
<img width="1656" alt="cs 2023-07-07 at 15 15 49@2x" src="https://github.com/metrico/qryn/assets/1182597/f81b14e7-497a-48e3-ae9d-597ecccf2e86">

**Comment by nchopra** [comment]
Tried `v2.3.2` to `v2.3.5` - can reproduce in all.

**Comment by lmangani** [comment]
Reproduced. Fix attempt in progress. I was testing on a future system unintentionally :)

**Comment by nchopra** [comment]
Super! works now :)
Thanks @lmangani @akvlad for the quick turnaround!

**Comment by lmangani** [comment]
It's a pleasure thanks for the feedback and for being active part of the **qryn** community!
