### ISSUE TITLE
qryn + InfluxDB Edge (3.0)

### ISSUE THREAD

**Issue by wahmedswl** [metrico/qryn#348]
Hi!

Is there any documentation etc to use qryn with InfluxDB. Its mentioned in the Readme about InfluxDB but no instructions in documentation about how. So, if you guys can give hints etc.

Thanks

**Comment by lmangani** [comment]
Thanks for your interest @wahmedswl `qryn-iox` is coming soon!
We'll release the integration as soon as InfluxDB Edge is consolidated and officially distributed. If you'd like to join the early testing, jump on our matrix channels.

**Comment by wahmedswl** [comment]
@lmangani Thanks for your reply. In term of compute, InfluxDB will be cheaper than ClickHouse? S3 is supported in both and we need to query the data outside so we need SQL which provides both now.

Thanks

**Comment by lmangani** [comment]
@wahmedswl it's too soon to tell, we're just at the beginning of this journey and Clickhouse is hard to beat on speed. 
I'd say they are for different usecases, and the cost effectiveness might be interesting to see but ultimately, benchmarking and user feedback will decide.

**Comment by wahmedswl** [comment]
@lmangani 💯 right that ClickHouse is hard to beat on Speed. Yeah, we are primarily focused on COST.

Thanks
