### ISSUE TITLE
Clickhouse + Qryn

### ISSUE THREAD

**Issue by Xantorero** [metrico/qryn#355]
Hello! 

I need some help integrating Grafana - Qryn - Clickhouse.

I have this stack:
```
                [Grafana]
                    |
                  [Qryn]
                    |
               [Clickhouse]
                    |
          [OpenTelemetry Collector]
          |      |        |        |
          [Metric exporters, Promtail]
```

I gather various metrics, logs and traces and store it in Clickhouse with OpenTelemetry Collector (official image), I wanted to use Qryn as a backend and middleman between Grafana and Clickhouse. But when I add Prometehus source in Grafana and connect it to Qryn, there are no metrics visible while creating queries, even though they are present in Clickhouse. Is there any naming for the tables with metrics logs and traces so Qryn can see them? For now I have named them otel_metrics_xyz where xyz is server name (multiple servers).

Is it necessary to use Qryn-otel-collector to ingest data into Clickhouse? If it is possible, please help.

Best Regards,
Adam

**Comment by lmangani** [comment]
Hello @Xantorero 

> Is it necessary to use Qryn-otel-collector to ingest data into Clickhouse? If it is possible, please help.

Yes, you need to store into clickhouse using either the qryn-collector or the qryn APIs to support our fingerprinting. 
Which formats are you ingesting? We support quite a lot [out of the box](https://qryn.metrico.in/#/support)

**Comment by Xantorero** [comment]
Oh, ok - so not using the qryn collector was the case (it totally makes sense now)! Thank You for quick answer, this saves me a lot of "What I am doing wrong" hours :) 

Before I close this issue: How often do You update the otel-collector version?

**Comment by lmangani** [comment]
@Xantorero we update it as often as users want or need it - there's a PR coming updating it to the latest otel version but mind the only difference is our exporter, and everything else is native/stock. Any suggestions there?

**Comment by Xantorero** [comment]
No, its perfect for me! Thank You again for the help and keep up the good work :)
