### ISSUE TITLE
issue starting qryn with pm2 and node21

### ISSUE THREAD

**Issue by tsearle** [metrico/qryn#375]
0|qryn     | Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/lib/node_modules/qryn/qryn.mjs not supported.
0|qryn     | Instead change the require of /usr/lib/node_modules/qryn/qryn.mjs to a dynamic import() which is available in all CommonJS modules.
0|qryn     |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23) {
0|qryn     |   code: 'ERR_REQUIRE_ESM'
0|qryn     | }
0|qryn     | Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/lib/node_modules/qryn/qryn.mjs not supported.
0|qryn     | Instead change the require of /usr/lib/node_modules/qryn/qryn.mjs to a dynamic import() which is available in all CommonJS modules.
0|qryn     |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23) {
0|qryn     |   code: 'ERR_REQUIRE_ESM'
0|qryn     | }
0|qryn     | Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/lib/node_modules/qryn/qryn.mjs not supported.
0|qryn     | Instead change the require of /usr/lib/node_modules/qryn/qryn.mjs to a dynamic import() which is available in all CommonJS modules.
0|qryn     |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23) {
0|qryn     |   code: 'ERR_REQUIRE_ESM'
0|qryn     | }^C
qryn@ip-10-150

**Comment by lmangani** [comment]
Thanks @tsearle could you kindly check if npm package qryn@3.0.6 resolves this issue?

We appreciate the reports! Dual stacking node/bun is proving to be less straightforward than expected, but its mostly cosmetic adjustments, the core code is unrelated.

**Comment by tsearle** [comment]
it seems to be working, but I think I'll stick with systemd, as it is simpler now that I have it already setup :-)

**Comment by lmangani** [comment]
@tsearle thanks for the confirmation, we can add the systemd method to the docs if you feel its useful for others

**Comment by lmangani** [comment]
Resolved in 3.0.6
