### ISSUE TITLE
error when trying to query prometheus

### ISSUE THREAD

**Issue by tsearle** [metrico/qryn#383]
<img width="661" alt="Screenshot 2023-11-10 at 08 13 28" src="https://github.com/metrico/qryn/assets/4540323/ed6b10ec-931b-4101-825c-c11acd28d405">

When searching the code the culprit seems as follows:
https://github.com/metrico/qryn/blame/34e2b07c68d1b11d6222e6f9b256f61b3c4f43a5/wasm_parts/main.js#L170

```

    fs.writeFileSync('req.txt', query)
    fs.writeFileSync('data.bin', writer.buffer())
```

according to git annotate, it seems it is some debug code that accidently slipped in 4 days ago

**Comment by lmangani** [comment]
Released in 3.0.13
