### ISSUE TITLE
Decommission stddev_over_time usage

### ISSUE THREAD

**Issue by tsearle** [metrico/qryn#389]
I'm not putting the fault agains the dashboard as it seems a bug internal to qryn...

Nov 14 06:37:29 ip-10-150-3-37 qryn[557]: Empty <[Object: null prototype] {}> {
Nov 14 06:37:29 ip-10-150-3-37 qryn[557]:   end: '1699943820',
Nov 14 06:37:29 ip-10-150-3-37 qryn[557]:   query: 'stddev_over_time(heplify_method_response[1m]) by (method, response)',
Nov 14 06:37:29 ip-10-150-3-37 qryn[557]:   start: '1699857420',
Nov 14 06:37:29 ip-10-150-3-37 qryn[557]:   step: '60'
Nov 14 06:37:29 ip-10-150-3-37 qryn[557]: }
Nov 14 06:37:29 ip-10-150-3-37 qryn[557]: PSQLError: 1:47: parse error: unexpected <by>
Nov 14 06:37:29 ip-10-150-3-37 qryn[557]:     at module.exports.rangeQuery (/usr/lib/node_modules/qryn/promql/index.js:24:13)
Nov 14 06:37:29 ip-10-150-3-37 qryn[557]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Nov 14 06:37:29 ip-10-150-3-37 qryn[557]:     at async Object.handler (/usr/lib/node_modules/qryn/lib/handlers/prom_query_range.js:22:20)

**Comment by lmangani** [comment]
@tsearle we cannot reproduce this with the error alone. please add how to reproduce.

**Comment by tsearle** [comment]
The query is 
stddev_over_time(heplify_method_response[1m]) by (method, response)

from the dashboard 
https://github.com/sipcapture/homer-docker/blob/main/all-in-one/grafana/provisioning/dashboards/SIP_Stats.json

if you want me to run a query to run a dump of data

**Comment by lmangani** [comment]
This query was part of our promql2logql transpiler but its not actually supported by prometheus.
Now that we feature wasm prometheus, we'll replace the function with a proper one.

**Comment by lmangani** [comment]
Completed with https://github.com/sipcapture/homer-docker/commit/0810718fe4c0b5f5415efcdc71c26ab97ffbc368
