### ISSUE TITLE
Qryn bun get metrics error

### ISSUE THREAD

**Issue by deathalt** [metrico/qryn#410]
3.0.25-bun version of qryn return

`: Unreachable code should not be executed (evaluating '_wasm.exports.onDataLoad(reqId)') `

in Grafana when trying to get metrics.

Node version works fine.

**Comment by deathalt** [comment]
I found the cause of the error, most likely you will not be able to reproduce it.

It happens when I request more than >100 million metrics. By decreasing the time interval the error disappears.

I suggest to close this bug. or start a new bug with a request to increase the requested amount of metrics.

**Comment by lmangani** [comment]
@deathalt thanks for the clarification. We can keep this issue, I'll modify the title and we'll add the setting as the goal.
We appreciate your reports, please let us know if you spot any other area where improvements can be beneficial!

**Comment by akvlad** [comment]
@deathalt v3.0.26 has the ADVANCED_PROMETHEUS_MAX_SAMPLES configuration option may resolve the problem. Feel free to check.

**Comment by deathalt** [comment]
tested with qxip/qryn:3.0.26-bun and ADVANCED_PROMETHEUS_MAX_SAMPLES: 5000000

everything is great

thanks!
