### ISSUE TITLE
Why limit MaxSamples to 100000?

### ISSUE THREAD

**Issue by lance0805** [metrico/qryn#411]
Sometimes our metrics are much larger than that, prometheus defaults to 5 million(https://prometheus.io/docs/prometheus/latest/command-line/prometheus/#flags) and I'm wondering why we need to limit that?

https://github.com/metrico/qryn/blob/2fe921a75d5449a4528cc1911b7845f10566c98f/wasm_parts/main.go#L118
`panic: query processing would load too many samples into memory in query execution`

**Comment by akvlad** [comment]
Hello @lance0805 
qryn should protect itself from the OOM failures. But the parameter can be configurable.

**Comment by lance0805** [comment]
Got it, I'll see how to configure it, thanks a lot!

**Comment by akvlad** [comment]
Oh. The configuration for the parameter is more of a plan than the implemented  feature. Sorry for the misunderstanding.

**Comment by lance0805** [comment]
It’s okay, I’m looking forward to this improvement, thank you again

**Comment by akvlad** [comment]
@lance0805 v3.0.26 has the `ADVANCED_PROMETHEUS_MAX_SAMPLES` to configure what you requested. Feel free to try.

**Comment by lance0805** [comment]
@akvlad great, I've tested this parameter, thanks a lot!
