### ISSUE TITLE
Inserted 'NaN' values are stored as zero in samples_v3

### ISSUE THREAD

**Issue by mat3733** [metrico/qryn#418]
To reproduce: 

in your promwrite.sh test script :
go run main.go -u http://localhost:3100/api/v1/prom/remote/write -t __name__:foobar -d $dd,NaN

The 'NaN' string is properly parsed into Float64 by the promremotecli go client
but still ended up as a zero value in samples_v3.

**Comment by lmangani** [comment]
Thanks for the report @mat3733 we'll look into after this and find a solution

**Comment by akvlad** [comment]
@mat3733 
qryn 3.0.28 will filter out all the NaN values. feel free to update.

**Comment by mat3733** [comment]
Thanks for your quick reactivity but actually, you have done the exact opposite of what we need.
My issue description was not clear, I'm sorry for this.

For our needs, 'NaN' values are very important to be kept in our metrics database.
It means that the device we're collecting metrics from has been down.

In the initial issue, I was complaining that the 'NaN' values were converted to zero values (which can be a real value for a metric).
I think it would be more useful if the 'NaN' values were properly inserted in the Clickhouse database (which supports them for a Float64 value).

**Comment by mat3733** [comment]
Closed by mistake. Please consider previous message.

**Comment by akvlad** [comment]
Well, NaN values are questionable about how to work further. 
`max_over_time(metric_with_NaNs[10m])`  how to process this kind of metrics
how to represent NaNs in a chart.

If a device stops producing anything, you can figure it out with `absent_over_time` function. I need some investigation of how to treat `NaN ` values correctly.

**Comment by mat3733** [comment]
Indeed, our specific usage of NaN may be doubtful but still : inserting 0 instead of 'NaN' or ignoring inserts with NaN is kind of a bug.

**Comment by akvlad** [comment]
@mat3733 
qryn 3.0.28 will write the NaN values as NaN into the samples_v3 table. Feel free to update

**Comment by akvlad** [comment]
Closing the issue then.
Thanks for the participation.
