### ISSUE TITLE
Unexpected metrics gaps

### ISSUE THREAD

**Issue by deathalt** [metrico/qryn#421]
` histogram_quantile(0.5, sum by(le) (rate(http_server_request_duration_seconds_bucket{job="Service", instance=~""}[1m]))) `

return point for every minute

` histogram_quantile(0.5, sum by(le) (rate(http_server_request_duration_seconds_bucket{job="Service", instance=~""}[30s]))) `

return nothing, as all values < 1m

in request  ` http_server_request_duration_seconds_bucket{job="Service", instance=~""} ` metrics exists for every 15 seconds

` rate(http_server_request_duration_seconds_bucket{job="Service", instance=~""}[60s]) `

return data for every minute

` rate(http_server_request_duration_seconds_bucket{job="Service", instance=~""}[59s]) `

return nothing

I'm sent same data from otel collector to qryn and prometheus and all requests to prometheus works fine, but qryn return nothing without any errors.

![image](https://github.com/metrico/qryn/assets/35489816/ad35f16f-383a-4dc5-97ca-1714351f9e4b)

![image](https://github.com/metrico/qryn/assets/35489816/0e11561c-e82e-41ba-873a-a7b9a794dbf6)

![image](https://github.com/metrico/qryn/assets/35489816/fb9b80e2-b829-4ca8-93d3-eddb4676765b)

**Comment by akvlad** [comment]
@deathalt should be fixed in 3.0.30. Feel free to update.

**Comment by deathalt** [comment]
@akvlad now everything works

Great job, thanks! I'm closing the issue, but feel free to reopen it if needed.
