### ISSUE TITLE
Loki json formatter long response

### ISSUE THREAD

**Issue by deathalt** [metrico/qryn#422]
When I receive logs from qryn without any format like ` {job="Service", level=~"INFO"} |= `` `, everything works great. However, if I attempt to use a format like ` {job="Service", level=~"INFO"} |= `` | json `, the response time exceeds 30 seconds.

I've checked the SQL request generated by qryn, and a direct request to ClickHouse has a response time of 1-2 seconds.

What can be the problem?

**Comment by akvlad** [comment]
@deathalt `json` is the slowest parser in the app. It's implemented via the javascript's `JSON.parse` operator.
please try `| json label="a.b[0].c" `. This will wlrk much faster.

Please always prefer `| regexp "..."` over `|json a="b"` over `|json`

**Comment by deathalt** [comment]
@akvlad oh, yep

using |json a="b" is pretty good,

Want to close this issue, or you have plans to speed up json parser?

**Comment by akvlad** [comment]
No. I can't speed it up. Sorry.
