### ISSUE TITLE
No such file or directory error when starting qryn

### ISSUE THREAD

**Issue by gabrielgontariu** [metrico/qryn#427]
Hello

After installing qryn I get this error when trying to start the process:
Error: ENOENT: no such file or directory, open 'view/index.html'
at /usr/lib/node_modules/qryn/qryn_node.js:441:20

installed with **npm install -g qryn** on ec2 debian
**3.0.21 update to latest qryn-view** is the first version where this bug can be reproduced.

**Comment by akvlad** [comment]
@gabrielgontariu should be fixed in 3.0.31 . Feel free to update.

**Comment by gabrielgontariu** [comment]
@akvlad @lmangani  thanks for the fix. I will test as soon as the package gets into npm

this is the latest release in there: 
published 3.0.28 • 9 days ago

**Comment by lmangani** [comment]
Sorry about the disruption, we had to update the publishing pipeline. 3.1.0 is published and ready to test.
