### ISSUE TITLE
Qryn not showing any data on grafana dashboard

### ISSUE THREAD

**Issue by gauravpareekk** [metrico/qryn#443]
Hi!

The application is pushing data at endpoint
xxxxx:12345/collect

However, we're unable to see the data in grafana dashboard which is linked with qryn. 

Any pointers or places I can look into for errors?

**Comment by lmangani** [comment]
Hello @gauravpareekk not sure what you might be referring to here. Could you describe your setup in mode detail? 
Neither the port or the API path appear to be matching qryn...

**Comment by gauravpareekk** [comment]
Hello @lmangani I'm following this blog to push data from my web app
https://blog.qryn.dev/grafana-faro-qryn

Based on the blog link.  I'm pushing data to an endpoint 
    <script>
window.initFaro = function() {
        window.GrafanaFaroWebSdk.initializeFaro({
                app: { name: 'xxxxx' },
                url: 'http://xxxx:12345/collect',
        });
};
</script>

However, I'm not seeing any data on the grafana dashboard. I've question:
- is the application pushing to the right endpoint?

**Comment by lmangani** [comment]
@gauravpareekk so you're sending data to **Grafana Agent** which in turn should be configured to insert into **qryn**. Correct?

**Comment by gauravpareekk** [comment]
yes, that's correct

**Comment by lmangani** [comment]
Troubleshoot logs from your sender, from Grafana Agent and from qryn for potential errors.
