### ISSUE TITLE
Pyroscope qryn cant select by multiple labels

### ISSUE THREAD

**Issue by tomershafir** [metrico/qryn#452]
For example time series exists:
<img width="1712" alt="Screenshot 2024-02-01 at 18 46 50" src="https://github.com/metrico/qryn/assets/86107951/79905deb-9c3f-40d6-95fe-2485f61d9a2d">
But not selected:
<img width="1712" alt="Screenshot 2024-02-01 at 18 49 55" src="https://github.com/metrico/qryn/assets/86107951/ec3eaca3-22d6-4000-958a-2df9d6ca333d">

**Comment by akvlad** [comment]
@tomershafir should be fixed in 3.2.2

**Comment by tomershafir** [comment]
lgtm, thanks!
