### ISSUE TITLE
Feature Request: Trino support

### ISSUE THREAD

**Issue by bcarlock-mycarrier** [metrico/qryn#470]
Trino is a crazy fast query engine that we would like to start using as a caching/fast data layer between Qryn and Clickhouse. It would also provide the added benefit of enabling connectivity between Qryn and any other Trino supported storage. [Full List](https://trino.io/docs/current/connector.html)
[Clickhouse](https://trino.io/docs/current/connector/clickhouse.html) is a standard connection for Trino.
There are some minor SQL dialect differences as noted in the link above.

[Here](https://github.com/regadas/trino-js-client) is an existing project which implements a Javascript client for Trino.

**Comment by lmangani** [comment]
@bcarlock-mycarrier thanks for the proposal. qryn is pretty tightly integrated with ClickHouse and uses several advanced techniques to achieve its results, most likely unviable with other supported option - one of our design principles is to keep things simple with qryn-js and while adding Trino as an option could be generally interesting, adding another layer of complexity and moving parts would require substantial arguments in favor.  

Feel free to let us know more about what your reasoning and experience is and what limitations you are trying to get around.
If you decide to embark into this challenge we'll gladly support your efforts and assist as we can!
