### ISSUE TITLE
Booleans parsed from environment in utterly confusing ways

### ISSUE THREAD

**Issue by bzed** [metrico/qryn#476]
Hi,

there are various "boolean" style config settings, which are parsed in different ways. For example:

https://github.com/metrico/qryn/blob/9da57a75cf666dad92fab1f7a91daecfbf55bbe0/common.js#L104

at least compares the value with 1. Not sure why it needs a lambda, but it works. According to the documentation the default is false, so I would expect the right setting to be 'true' and not 1.

https://github.com/metrico/qryn/blob/9da57a75cf666dad92fab1f7a91daecfbf55bbe0/common.js#L129

Even worse. `READONLY=false` in the environment will evaluate to true. :crying_cat_face:  Basically everywhere `if (readonly)` is being used.

I did not go trough the other boolean style config options, but please find a unified way to set such options and document it.

Thanks,

Bernd

**Comment by lmangani** [comment]
Thanks for raising this good point @bzed we need to sanitize bool settings in a standardized fashion.
We'll add this to the quick roadmap to improve the experience.

**Comment by akvlad** [comment]
@bzed the problem you mentioned was... well, taken under control
since 3.2.14 all the boolean env vars should be:
- `no, n, false, 0` and missing variable is considered as false
- `yes, y, true, 0` is considered as true

I hope the solution satisfies everyone.
Thanks for the heads up.

**Comment by lmangani** [comment]
Closing as completed! Feel free to reopen if the issue persists
