### ISSUE TITLE
BULK_MAXAGE / BULK_MAXSIZE - insert limits!?

### ISSUE THREAD

**Issue by bzed** [metrico/qryn#497]
Hi,

according to the documentation there is are
BULK_MAXSIZE
BULK_MAXCACHE
settings, but I can't find them in the code.

Is there any undocumented way I didn't find to limit the size of the inserts? 

Thanks,

Bernd

**Comment by akvlad** [comment]
Now it sends as many as you can ingest during 100ms.
Also we have a limit for ingestion of 50MB/sec before a request proceeds to be parsed.

**Comment by akvlad** [comment]
@bzed can you suggest what is the best solution you suggest about the `BULK_MAXSIZE` configuration?
What should happen if the request overflows the configured value?

**Comment by akvlad** [comment]
# Bulk size configuration
*since 3.2.23*

Two env vars were introduced:

-    BULK_MAX_SIZE_BYTES - max size of the bulk in bytes (default - infinite)
-    BULK_MAX_AGE_MS - max age of the bulk in milliseconds (default - 100), can't be less than 100

**Comment by lmangani** [comment]
@bzed this was implemented. Let us know if you have any feedback and/or comments.

Cloding as completed!
