### ISSUE TITLE
distributed table (time_series_gin_dist) is not always used in cluster mode

### ISSUE THREAD

**Issue by R-omk** [metrico/qryn#504]
https://github.com/metrico/qryn/blob/52d9c5dc20b32285726983970b6aba85b5cfe2f8/parser/registry/stream_selector_operator_registry/stream_selector_indexed_registry.js#L77

https://github.com/metrico/qryn/blob/52d9c5dc20b32285726983970b6aba85b5cfe2f8/promql/index.js#L106

**Comment by akvlad** [comment]
In this place time_series gin is used in a subrequest of the distributed table.

**Comment by R-omk** [comment]
ok, I see that there are other places where a distributed table joins a local one, if that’s how it’s intended and it’s correct, then close this ticket.
I don't have any bug, it just seemed like logged query was wrong.

**Comment by lmangani** [comment]
Any question is a great question if it helps understand the underlying logic best. Thanks for opening and let us know if you notice any performance issue related to the current design.
