### ISSUE TITLE
option to create schema end exit process

### ISSUE THREAD

**Issue by R-omk** [metrico/qryn#505]
When installing a product, it need the ability to start migration job (scheme installation) and then complete the process. At the same time, for other modes, disable schema creation.

something like  process_mode:
-reader (just for read api )
-writer ( for  write only )
-migration (only create clickhouse schema and exit )

**Comment by lmangani** [comment]
Good logical points, let's make this happen.

**Comment by akvlad** [comment]
What do we need reader and writer process mode for?
They have different non-colliding api routes.

**Comment by R-omk** [comment]
> What do we need reader and writer process mode for?

do it at your discretion, I simply use them separately, and each is configured with its own access to CH, 
the reader will not be able to write even if we tries, 
but it’s better if the reader doesn’t even try..

**Comment by akvlad** [comment]
# Qryn operation Mode

## MODE env var was introduced. It can have one of 3 values:

- writer - only writing paths
-  reader - only reading paths
-    init_only - initialize the database and exit
-    all - reading and writing paths

**Comment by lmangani** [comment]
@R-omk this was implemented. Let us know if this fulfills your requirements and/or if you have comments.

Closing as completed, pending feedback.
