### ISSUE TITLE
Support Ingesting Logs Through OTLP Protocol for Qryn

### ISSUE THREAD

**Issue by deathalt** [metrico/qryn#531]
Otel collector plans to depricate loki exporter (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/19215)

We really don't want to move from qryn to grafana stack, but if the loki exporter will be depricated we have no options, except to come up with some workaround via grafana alloy, which we don't want to do either.

It would be great to support ingest otlp protocol logs

**Comment by lmangani** [comment]
WIP. Ingesting OTLP logs shouldn't be complex. Where there's a will, there a way.

> We really don't want to move from qryn to grafana stack

I'm curious. How would this change affect qryn differently than Grafana? 
Also nothing would prevent us from keeping the loki exporter in our collector if we wanted to do so. 

>  workaround via grafana alloy, which we don't want to do either.

Isn't Alloy an otel-collector itself with a nicer syntax? I doubt Grafana will remove their own exporters. I like alloy so far.

**Comment by deathalt** [comment]
> I'm curious. How would this change affect qryn differently than Grafana?
> Also nothing would prevent us from keeping the loki exporter in our collector if we wanted to do so.

I'm the same as always.
By grafana stack I mean loki + mimir + tempo.
They all have otlp ingest support.

> Isn't Alloy an otel-collector itself with a nicer syntax? I doubt Grafana will remove their own exporters. I like alloy so far.

it may be cool, but we're not ready to move to it.
alloy still supports loki http ingest through /v1/push

**Comment by lmangani** [comment]
Thanks for sharing more details. We're definitely adding the ingestion capabilities in pure qryn style.
The reference formats used are here: https://github.com/open-telemetry/opentelemetry-proto/tree/main/opentelemetry/proto

**Comment by akvlad** [comment]
@deathalt otlp export is released in 3.2.26

The example of the collector configuration is here: https://github.com/metrico/qryn/pull/534#issue-2408677641

**Comment by lmangani** [comment]
Closing as implemented. @deathalt let us know if you get around trying this and have feedback.
