### ISSUE TITLE
Parsing queries destroys database performance 

### ISSUE THREAD

**Issue by KhafRuslan** [metrico/qryn#541]
Instance parameters: 24 core, 40GB RAM, 2GB SWAP 
Query:
![image](https://github.com/user-attachments/assets/1a678c24-ecc7-4fac-aeec-abf65aea1de8)
The result of this query on the performance of the database 
![image](https://github.com/user-attachments/assets/5d611b95-e255-4f18-a280-d558b23efa72)
The SQL query looks like this 
![image](https://github.com/user-attachments/assets/61c44625-420a-42df-bf7d-380992fc15ab)

**Comment by lmangani** [comment]
Thanks for the report @KhafRuslan 
Depending on the object size the `json` parser can be quite expensive and works much faster if you specify the fields to extract.
PS: Please attach text rather than screenshots whenever possible.
