### ISSUE TITLE
Retention policy configuration

### ISSUE THREAD

**Issue by qqu0127** [metrico/qryn#545]
Hi team, I'm new to qryn and clickhouse but with have some hands-on experience with loki. 
I'm trying to understand how I can configure the log retention policy in qryn like in loki. I imagine it should be in a env config, for deletion or compression or cold storage etc. I read the docs and wiki but didn't find those helpful. Could someone please help? Thanks in advance.

**Comment by akvlad** [comment]
Hello @qqu0127 .
 https://qryn.metrico.in/#/env?id=parameters - 

| LABELS_DAYS | 7 | Max Days before Label rotation |
| --- | --- | --- |
| SAMPLES_DAYS | 7 | Max Days before Timeseries rotation |

These two configuration options are to configure TTL . 
In most cases they should have the same value.

**Comment by qqu0127** [comment]
> Hello @qqu0127 . https://qryn.metrico.in/#/env?id=parameters -
> 
> LABELS_DAYS	7	Max Days before Label rotation
> SAMPLES_DAYS	7	Max Days before Timeseries rotation
> These two configuration options are to configure TTL . In most cases they should have the same value.

Got it, thanks a lot.  
As side note, it'd be great if the doc can have some more clarification, also TTL or retention sounds more clear than rotation.

**Comment by lmangani** [comment]
All settings are documented here: https://qryn.metrico.in/#/env

**Comment by Girgitt** [comment]
I think these configuration options should be described more explicitly in the documentation and examples. Currently, nothing can be found under the terms "retention" or "ttl." on wiki.

For anyone interested in validating if configuration was successfully applied here is  ClickHouse v24.5 SQL that shows TTL options for qryn tables: 

```
 :) SELECT 
    database,
    name AS table_name,
    engine,
    substring(
        create_table_query, 
        position(create_table_query, 'TTL'), 
        position(create_table_query, ' SETTINGS') - position(create_table_query, 'TTL')
    ) AS ttl_expression
FROM 
    system.tables
WHERE 
    database = 'qryn'
    AND create_table_query LIKE '%TTL%';

SELECT
    database,
    name AS table_name,
    engine,
    substring(create_table_query, position(create_table_query, 'TTL'), position(create_table_query, ' SETTINGS') - position(create_table_query, 'TTL')) AS ttl_expression
FROM system.tables
WHERE (database = 'qryn') AND (create_table_query LIKE '%TTL%')

Query id: 3557aaf8-7a7e-481c-8a5b-23cb2815629e

    ┌─database──────┬─table_name─────────────┬─engine─────────────┬─ttl_expression────────────────────────────────────────────────┐
 1. │ qryn │ profiles               │ MergeTree          │ TTL toDateTime(timestamp_ns / 1000000000) + toIntervalDay(30) │
 2. │ qryn │ profiles_series        │ ReplacingMergeTree │ TTL date + toIntervalDay(30)                                  │
 3. │ qryn │ profiles_series_gin    │ ReplacingMergeTree │ TTL date + toIntervalDay(30)                                  │
 4. │ qryn │ profiles_series_keys   │ ReplacingMergeTree │ TTL date + toIntervalDay(30)                                  │
 5. │ qryn │ samples_v3             │ MergeTree          │ TTL toDateTime(timestamp_ns / 1000000000) + toIntervalDay(30) │
 6. │ qryn │ tempo_traces           │ MergeTree          │ TTL toDateTime(timestamp_ns / 1000000000) + toIntervalDay(30) │
 7. │ qryn │ tempo_traces_attrs_gin │ ReplacingMergeTree │ TTL date + toIntervalDay(30)                                  │
 8. │ qryn │ tempo_traces_kv        │ ReplacingMergeTree │ TTL date + toIntervalDay(30)                                  │
 9. │ qryn │ time_series            │ ReplacingMergeTree │ TTL date + toIntervalDay(30)                                  │
10. │qryn │ time_series_gin        │ ReplacingMergeTree │ TTL date + toIntervalDay(30)                                  │
    └───────────────┴────────────────────────┴────────────────────┴───────────────────────────────────────────────────────────────┘

10 rows in set. Elapsed: 0.008 sec. 

```

**Comment by qqu0127** [comment]
@Girgitt +1 on the documentation wording.
Great work on the TLL query, love it.
