### ISSUE TITLE
qryn loki crash with certain query

### ISSUE THREAD

**Issue by qqu0127** [metrico/qryn#565]
Hi team, I ran into the following crashing issue. The qryn app crash when I query logs from Grafana, the query is fairly simple (just specify a namespace and a app), and it can be reproduced. Appreciate if someone can take a look. Thanks.

Update: 
qryn version 3.2.30

---

WITH sel_a AS (select `samples`.`string` as `string`,`samples`.`fingerprint` as `fingerprint`,samples.timestamp_ns as `timestamp_ns` from qryn_cluster_updated.samples_v3_dist as `samples` where ((`samples`.`timestamp_ns`   between 1725519084289000000 and 1725522684289000000) and (`samples`.`type` in (0,0))) and (samples.fingerprint IN (select `sel_1`.`fingerprint` from (select `fingerprint` from `qryn_cluster_updated`.`time_series_gin` where ((`key` = 'namespace') and (`val` = 'MY_NAMESPACE'))) as `sel_1`  inner any  join (select `fingerprint` from `qryn_cluster_updated`.`time_series_gin` where ((`key` = 'app') and (`val` = 'MY_APP_NAME))) as `sel_2` on `sel_1`.`fingerprint` = `sel_2`.`fingerprint`)) order by `timestamp_ns` desc limit 1000) select JSONExtractKeysAndValues(time_series.labels, 'String') as `labels`,sel_a.* from sel_a left any join `qryn_cluster_updated`.`time_series_dist` AS time_series on `sel_a`.`fingerprint` = time_series.fingerprint order by `labels` desc,`timestamp_ns` desc
2024-09-05T07:51:24.518143750Z /app/node_modules/stream-shift/index.js:16
    return state.buffer[0].length
                           ^

TypeError: Cannot read properties of null (reading 'length')
    at getStateLength (/app/node_modules/stream-shift/index.js:16:28)
    at shift (/app/node_modules/stream-shift/index.js:6:99)
    at Duplexify._forward (/app/node_modules/peek-stream/node_modules/duplexify/index.js:168:35)
    at Duplex.onreadable (/app/node_modules/peek-stream/node_modules/duplexify/index.js:134:10)
    at Duplex.emit (node:events:519:28)
    at emitReadable_ (node:internal/streams/readable:832:12)
    at onEofChunk (node:internal/streams/readable:810:5)
    at readableAddChunkPushByteMode (node:internal/streams/readable:464:5)
    at Readable.push (node:internal/streams/readable:390:5)
    at deflator.onEnd (/app/qryn_node.js:142:19)

Node.js v20.17.0

**Comment by lmangani** [comment]
@qqu0127 Thanks for the report! 
Could you please provide the original query as well? The transpiled version only makes sense with the original.

**Comment by qqu0127** [comment]
> @qqu0127 Thanks for the report! Could you please provide the original query as well? The transpiled version only makes sense with the original.

Sure. The query as below, to query for the last 5 minutes or longer time.

{namespace="MY_NAMESPACE", app="MY_APP_NAME"} |= ``

**Comment by akvlad** [comment]
@qqu0127 are you using docker or a separate installation?

**Comment by qqu0127** [comment]
> @qqu0127 are you using docker or a separate installation?

@akvlad It's on K8S with docker image. Also FYI, it's running version 3.2.30

**Comment by akvlad** [comment]
@qqu0127 We have fixed exactly this in 3.2.31. Please try it.

**Comment by qqu0127** [comment]
@akvlad Wow, lucky me. Thanks a lot, let me try that and get back...

**Comment by qqu0127** [comment]
@akvlad Deployed 3.2.31 and the issue resolved.
