### ISSUE TITLE
WIP: Build qryn-view from git submodule

### ISSUE THREAD

**Issue by lmangani** [metrico/qryn#566]
Proposal:

- [x] Create submodule for `qryn-view` in `qryn` repository
- [x] Update workflows to pull from `qryn-view` and build in `qryn` releases
- [x] Remove branch push action from `qryn-view` repository
  - https://github.com/metrico/qryn-view/commit/d9e96e55028c303dec5cdf83996ba55e8bd42d09

**Comment by lmangani** [comment]
@akvlad can we update and/or close as completed?

**Comment by akvlad** [comment]
completed in 3.2.32
