### ISSUE TITLE
axios error

### ISSUE THREAD

**Issue by tsearle** [metrico/qryn#594]
on rolling out a new qryn server  qryn@3.2.33

to qryn@3.2.35

`Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]: {"level":50,"time":1730197684051,"pid":11987,"hostname":"ip-10-153-17-38","name":"qryn","reqId":"req-59","err":"Database push error\nError: Database push error\n    at Worker.<anonymous> (/usr/lib/node_modules/qryn/lib/db/clickhouse.js:84:27)\n    at Worker.emit (node:events:519:28)\n    at MessagePort.<anonymous> (node:internal/worker:263:53)\n    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)\n    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)","msg":"Database push error"}
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]: {"level":30,"time":1730197684051,"pid":11987,"hostname":"ip-10-153-17-38","name":"qryn","reqId":"req-59","res":{"statusCode":500},"responseTime":173.01575500052422,"msg":"request completed"}
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]: {"level":50,"time":1730197684052,"pid":11987,"hostname":"ip-10-153-17-38","name":"qryn","reqId":"req-5a","err":"Database push error\nError: Database push error\n    at Worker.<anonymous> (/usr/lib/node_modules/qryn/lib/db/clickhouse.js:84:27)\n    at Worker.emit (node:events:519:28)\n    at MessagePort.<anonymous> (node:internal/worker:263:53)\n    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)\n    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)","msg":"Database push error"}
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]: {"level":30,"time":1730197684052,"pid":11987,"hostname":"ip-10-153-17-38","name":"qryn","reqId":"req-5a","res":{"statusCode":500},"responseTime":113.0183290001005,"msg":"request completed"}
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]: {"level":50,"time":1730197684052,"pid":11987,"hostname":"ip-10-153-17-38","name":"qryn","reqId":"req-5b","err":"Database push error\nError: Database push error\n    at Worker.<anonymous> (/usr/lib/node_modules/qryn/lib/db/clickhouse.js:84:27)\n    at Worker.emit (node:events:519:28)\n    at MessagePort.<anonymous> (node:internal/worker:263:53)\n    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)\n    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)","msg":"Database push error"}
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]: {"level":30,"time":1730197684052,"pid":11987,"hostname":"ip-10-153-17-38","name":"qryn","reqId":"req-5b","res":{"statusCode":500},"responseTime":107.75954400002956,"msg":"request completed"}
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]: {"level":50,"time":1730197684052,"pid":11987,"hostname":"ip-10-153-17-38","name":"qryn","reqId":"req-5c","err":"Database push error\nError: Database push error\n    at Worker.<anonymous> (/usr/lib/node_modules/qryn/lib/db/clickhouse.js:84:27)\n    at Worker.emit (node:events:519:28)\n    at MessagePort.<anonymous> (node:internal/worker:263:53)\n    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)\n    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)","msg":"Database push error"}
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]: {"level":30,"time":1730197684053,"pid":11987,"hostname":"ip-10-153-17-38","name":"qryn","reqId":"req-5c","res":{"statusCode":500},"responseTime":53.57408499997109,"msg":"request completed"}
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]: {"level":50,"time":1730197684050,"pid":11987,"hostname":"ip-10-153-17-38","name":"qryn","msg":"Code: 27. DB::Exception: Cannot parse input: expected ',' before: '{},\"string\":\"{\\\\\"PRIORITY\\\\\":\\\\\"6\\\\\",\\\\\"SYSLOG_FACILITY\\\\\":\\\\\"3\\\\\",\\\\\"SYSLOG_IDENTIFIER\\\\\":\\\\\"rtpengine\\\\\",\\\\\"_BOOT_ID\\\\\":\\\\\"f295982943754d2a97e6da8b5be0c6a8\\\\\",\\\\\"_CAP_EFFECTIV': (at row 1)\n: While executing ParallelParsingBlockInputFormat. (CANNOT_PARSE_INPUT_ASSERTION_FAILED) (version 24.6.1.4609 (official build))\n"}
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]: axiosError AxiosError: Request failed with status code 400
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]:     at settle (/usr/lib/node_modules/qryn/node_modules/axios/dist/node/axios.cjs:2019:12)
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]:     at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/qryn/node_modules/axios/dist/node/axios.cjs:3135:11)
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]:     at IncomingMessage.emit (node:events:531:35)
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]:     at endReadableNT (node:internal/streams/readable:1696:12)
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]:     at Axios.request (/usr/lib/node_modules/qryn/node_modules/axios/dist/node/axios.cjs:4287:41)
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]:     at async rawRequest (/usr/lib/node_modules/qryn/lib/db/clickhouse.js:1401:12)
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]:     at async TimeoutOrSizeThrottler._flush (/usr/lib/node_modules/qryn/lib/db/throttler.js:92:5)
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]:     at async TimeoutOrSizeThrottler.flush (/usr/lib/node_modules/qryn/lib/db/throttler.js:74:7)
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]:     at async /usr/lib/node_modules/qryn/lib/db/throttler.js:163:13
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]:     at async Promise.all (index 0)
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]:     at async Timeout._onTimeout (/usr/lib/node_modules/qryn/lib/db/throttler.js:160:9) {
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]:   code: 'ERR_BAD_REQUEST',
Oct 29 10:28:04 ip-10-153-17-38 qryn[11987]:   config: {
`

**Comment by tsearle** [comment]
value is missing

{
  "fingerprint": "302013289035268972",
  "timestamp_ns": "1730188927062345000",
  "value": {},

**Comment by akvlad** [comment]
As the problem fixed, closing the issue.
