### ISSUE TITLE
Grafana fails to load logs samples

### ISSUE THREAD

**Issue by mennotech** [metrico/qryn#601]
I'm testing qryn using metrico/qryn-minimal

I have the docker image (via WSL) running and supplied sample data using:

`curl -i -XPOST -H "Content-Type: application/json" http://localhost:3100/loki/api/v1/push --data '{"streams":[{"stream":{"type":"test"},"values":[['$(date +"%s%N")', "hello qryn"]]}]}'`

I am running Grafana (on Windows) locally and set up a loki data source pointing to http://localhost:3100

The following query shows a graph of number of test messages per 5 minutes

`rate({type="test"} [5m])`

However, when I try and expand the Logs sample, it fails with the following error: 

`Failed to load logs sample for this query
ReadString: expects " or n, but found 1, error found in #10 byte of ...|alues":[[17317098492|..., bigger context ...| "result": [{"stream":{"type":"test"},"values":[[1731709849262086000,"hello qryn"],[1731709825975030|...
`

Sorry, I'm still learning Grafana, and I'm not sure why this isn't working properly, is this a Grafana issue or qryn issue?

![Screenshot 2024-11-15 170532](https://github.com/user-attachments/assets/934258aa-1262-4d7b-8c8f-4544581aff0d)

**Comment by lmangani** [comment]
Hello @mennotech qryn-minimal is just an experiment and no longer expected to pass more than basic testing at this time since its based on a *very* unstable and unreliable backend. I would suggest experimenting with the standard qryn version.

**Comment by mennotech** [comment]
I was able to get this working with metrico/qryn-oss-demo. Thanks for the pointer.
