### ISSUE TITLE
Using cLoki with Distributed/Sharded Clickhouse

### ISSUE THREAD

**Issue by navinpai** [metrico/qryn#62]
Firstly, great project and I'm having quite some fun playing around with this _(and yes, we're all Clickhouse fans here)_ 😉 

---

I was wondering how to get cLoki running in distributed Clickhouse mode. I have a cluster set up where I have manually set up master + N shards with master having the tables defined with `ENGINE = Distributed` in `master` and regular clustered ingestion/querying works fine.

Was wondering how I can get cLoki to work in this distributed/clustered environment. I see a wiki page [which mentions a distributed schema](https://github.com/lmangani/cLoki/wiki/ClickHouse-Schema#database-schema-for-cluster), but nothing besides that anywhere in the project. Is support for this already present? I'd appreciate some pointers for this.

**Comment by akvlad** [comment]
Hello @navinpai ! Happy to see you interested in our small project! 
Now we don't have any distributed modes for cLoki, but you can do it manually. According the information I heard from @lmangani  the manual configuration is tested and it works.
So now we use 3 or 4 tables:
- time_series
- samples_v2
- samples_read
- samples (if you have legacy data)

You can manually rename them with the "_standalone" suffix. Then you can create distributed tables with the same names pointing to the standalone ones.
It should work. Please let us know if it works or not, I'll think about the way of how to automate it.

**Comment by navinpai** [comment]
Hey @akvlad
Thanks for the quick reply! I was able to get the distributed mode set up manually as you suggested above, but I had to make minor changes to cLoki code locally to avoid warnings/errors below. Specifically, 8a6aaf942936361eaf2642890881be8c6461f8b2 introduced some `ALTER TABLE` commands which aren't supported by the `DistributedEngine`, so you get warning/errors:

```
Unknown error field: Code: 36. DB::Exception: Cannot alter settings, because table engine doesn't support settings changes. (BAD_ARGUMENTS) (version 21.11.4.14 (official build))
Error: Code: 36. DB::Exception: Cannot alter settings, because table engine doesn't support settings changes. (BAD_ARGUMENTS) (version 21.11.4.14 (official build))

Unknown error field: Code: 48. DB::Exception: Alter of type 'MODIFY_TTL' is not supported by storage Distributed. (NOT_IMPLEMENTED) (version 21.11.4.14 (official build))
Error: Code: 48. DB::Exception: Alter of type 'MODIFY_TTL' is not supported by storage Distributed. (NOT_IMPLEMENTED) (version 21.11.4.14 (official build))
```

However, these are just warnings that don't affect ingestion directly _(and since I manually created the tables, I could just comment out these to remove the warning messages)_.

**Comment by lmangani** [comment]
@navinpai thanks for circling back your attempt! Indeed the alter wouldn't work as is if the storage engine changed. The ingestion will not suffer anything but the data will not be rotated out, growing indefinitely. We're happy to extend the current model to allow this more comfortably using this input

**Comment by lmangani** [comment]
@navinpai a couple changes in https://github.com/lmangani/cLoki/pull/60 will allow skipping alters

> LABELS_DAYS or SAMPLES_DAYS set to 0 will disable rotation/alter operations

**Comment by lmangani** [comment]
Thanks for the report @navinpai hopefully this is resolved. Please do feel free to share any observations or suggestions here or in new issues. We definitely want to offer options to support distributed tables out of the box, so any input is extremely valuable.

**Comment by navinpai** [comment]
@lmangani Was testing out the cloki API with a sharded clickhouse today, and came across another issue: The query_range API breaks on a distributed Clickhouse because it makes use of a distributed IN join.

### API
curl -G  "http://localhost:3100/loki/api/v1/query_range" --data-urlencode 'query={app="my-app"}'

### Logs

You can see the query that gets executed in `config.data` in the logs
```
GET /loki/api/v1/query_range
QUERY:  [Object: null prototype] {
  direction: 'BACKWARD',
  limit: '1000',
  query: '{app="my-app"}',
  start: '1637613289386000000',
  end: '1637616889386000000',
  step: '2'
}
Scanning Fingerprints...
Scanning Fingerprints...
Error: Request failed with status code 500
    at createError (/usr/local/lib/node_modules/cloki/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/cloki/node_modules/axios/lib/core/settle.js:17:12)
    at RedirectableRequest.handleResponse (/usr/local/lib/node_modules/cloki/node_modules/axios/lib/adapters/http.js:238:9)
    at RedirectableRequest.emit (node:events:390:28)
    at RedirectableRequest._processResponse (/usr/local/lib/node_modules/cloki/node_modules/follow-redirects/index.js:425:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/usr/local/lib/node_modules/cloki/node_modules/follow-redirects/index.js:57:10)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:390:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:623:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17) {
  config: {
    url: 'http://default:@localhost:8123/',
    method: 'post',
    data: "WITH str_sel as ( SELECT DISTINCT fingerprint, labels FROM cloki.time_series  WHERE JSONHas(labels, 'app') AND JSONExtractString(labels, 'app') = 'my-app' ), sel_a as ( SELECT  str_sel.labels as labels, samples.string as string, samples.fingerprint as fingerprint, samples.timestamp_ms as timestamp_ms FROM cloki.samples_read as samples  LEFT JOIN str_sel ON samples.fingerprint = str_sel.fingerprint WHERE samples.fingerprint IN (SELECT fingerprint FROM str_sel) AND timestamp_ms >= 1637613289385 AND timestamp_ms <= 1637616889385  ORDER BY timestamp_ms desc, labels desc  LIMIT 1000) SELECT  * FROM sel_a  ORDER BY labels desc, timestamp_ms desc  FORMAT JSONEachRow",
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/x-www-form-urlencoded',
      'User-Agent': 'axios/0.21.4',
      'Content-Length': 672
    },
.
.
.
```

If I run the query in Clickhouse directly, it gives: 

```
Code: 288. DB::Exception: Received from localhost:9000. DB::Exception: Double-distributed IN/JOIN subqueries is denied (distributed_product_mode = 'deny'). You may rewrite query to use local tables in subqueries, or use GLOBAL keyword, or set distributed_product_mode to suitable value.: While processing  cloki.time_series: While processing  LEFT JOIN str_sel ON samples.fingerprint = str_sel.fingerprint. (DISTRIBUTED_IN_JOIN_SUBQUERY_DENIED)
```

I tried using `distributed_product_mode = 'allow'` on Clickhouse, but that just changes the error to

```
Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: Received from 172.31.62.106:9000. DB::Exception: Table default.str_sel doesn't exist. (UNKNOWN_TABLE)
```

Any ideas around working around this?

**Comment by akvlad** [comment]
@navinpai I finished beta version of the clustered clickhouse support. It is in the clickhouse-cluster branch https://github.com/lmangani/cLoki/tree/clickhouse-cluster.
New configuration for cLoki is described in changelog https://github.com/lmangani/cLoki/blob/clickhouse-cluster/changelog.md

In order to properly install the distributed tables you should at least drop your distributed tables and samples_read table.

Please let us know if the new setup works on your environment.

**Comment by akvlad** [comment]
@navinpai Hello again. I have changed the strategy of logs sharding and finished a new version of it. 
Unfortunately it is incompatible with the one I created yesterday. But it passes all the backwards compatibility tests as well. 
---
Feel free to test. But as far as this functionality is in a testing branch, please keep your sensitive data backup so you can reimport it to the new version of data structures.

**Comment by navinpai** [comment]
Hey @akvlad I'll test this out. I tested out the changes in the parser yesterday and it seemed to work fine with a distributed cluster _(since I already had a manually created cluster)_, but will try to play around a bit with the E2E flow.

Thanks for the heads up about the data backup too.

**Comment by lmangani** [comment]
Converging the topic here: https://github.com/metrico/qryn/wiki/qryn-tables-replication-support
