### ISSUE TITLE
Configurable Partition options

### ISSUE THREAD

**Issue by mr-karan** [metrico/qryn#75]
We have a large deployment log cluster and store multiple year's worth of logs. For us, partitioning by date is more useful than partitioning by hour.

Would it be possible to have [this](https://github.com/lmangani/cLoki/blob/1e0d6ed077740042b0473dd7f75cd230a50d2377/lib/db/clickhouse.js#L185) configurable as a `PARTITION_INTERVAL` variable?

Probably we can take
- `weekly`
- `monthly`
- daily`
- `hourly`

as different options from user, fallback being the current `hourly`.

Thanks!

**Comment by lmangani** [comment]
@akvlad and @adubovikov any comments or suggestions here?

**Comment by adubovikov** [comment]
@mr-karan i suggestion to you make it daily because at the end you should not have a huge number of partitions in the table. You should not worry about huge file,  because scan will be by partition datetime key.

**Comment by lmangani** [comment]
Feel free to reopen if still interested for 3.x
